### ISSUE TITLE
【一般性问题】关于企业复杂网络环境下，本机IP无法正确定位的问题.

### ISSUE THREAD

**Issue by amao12580** [dangdangdotcom/elastic-job#1]
问题发生位置
工程：elastic-job-core，类：com.dangdang.ddframe.job.internal.env.RealLocalHostService，方法：getLocalHost().
![Uploading 1.jpg…]()

说明：对于一般性网络环境，代码段：InetAddress.getLocalHost();，可以正确的获取到本机的ip。
对于复杂的企业环境，企业网络管理员可能会进行部门子网、小组子网的划分，并最终链入企业主路由；
这样一台员工主机可能会有多个内网ip，代码段：InetAddress.getLocalHost();默认会返回当前主机链接到最近网络拓扑路径的路由所分配的子网ip。

综上，代码段：InetAddress.getLocalHost();得到的ip可能与实际链接到zookeeper的ip出现不一致。
可以想象的到，错误的将子网路由ip作为链接到zookeeper的ip，会导致同子网下，不同机器链接zookkeeper出现判断错误。

建议修改代码：https://github.com/amao12580/RSSReader/blob/master/core.base/src/main/java/per/rss/core/base/util/IPUtils.java

**Comment by terrymanu** [comment]
fixed

**Comment by amao12580** [comment]
已经完成bug回归测试，确认该问题已解决。
![1](https://cloud.githubusercontent.com/assets/4270177/10115573/fe62660e-643e-11e5-87c0-34dc6930c68c.jpg)
