### ISSUE TITLE
是否支持代码方式启动的Job中可取到Spring上下文？

### ISSUE THREAD

**Issue by caigy** [dangdangdotcom/elastic-job#108]
需求：Job的创建时根据代码逻辑动态控制，而非提前定义，在Job中需要使用由Spring上下文提供的bean。
        看过文档及elastic-job-example，JobMain中启动的Job，其用到的成员都是new出来的。是否可支持代码启动的Job可由Spring实例化，或取得Spring上下文？
        类似elastic-job-example中，JobMain里支持启动com.dangdang.example.elasticjob.spring.job.SimpleJobDemo的效果（此SimpleJobDemo的fooRepository是注入的）。
      谢谢。

**Comment by henrydh** [comment]
同遇到这个问题！

**Comment by terrymanu** [comment]
可以看一下com.dangdang.ddframe.job.spring.schedule.SpringJobScheduler创建Spring job的方式。
