### ISSUE TITLE
不支持Spring注解

### ISSUE THREAD

**Issue by cmkcmk181** [dangdangdotcom/elastic-job#109]
由于项目使用的是Spring，通过注解注入bean的，目前job是否支持注解方式？通过xml配置job方式无法获取通过注解注入的Bean

**Comment by terrymanu** [comment]
可以用代码举例子么，没有理解你的意思。
按照我粗浅的理解，用命名空间<job:simple xxx />这样配置的作业不能在作业中使用@Resource获取spring的bean么？
如果是这样，建议看一下example里面的com.dangdang.example.elasticjob.spring.job.SimpleJobDemo

**Comment by ZhangShufan15** [comment]
@cmkcmk181 task加上@Compoment试下
