### ISSUE TITLE
使用elastic-job 1.1.0版本，遇到The version of ZooKeeper being used doesn't support Container nodes

### ISSUE THREAD

**Issue by TNT733** [dangdangdotcom/elastic-job#112]
2016-06-21 11:41:46,619 [Curator-Framework-0] [ZKPaths.java:76] [WARN ZKPaths] - The version of ZooKeeper being used doesn't support Container nodes. CreateMode.PERSISTENT will be used instead.

使用elastic-job 1.1.0版本，启动遇到以上问题

看了下依赖，curator-client的版本是2.10.0，google了下，这个bug在2.9.0发现，之后的版本解决。不知道为什么还会报这个问题

控制台报完这句日志之后，就一直block掉了，进程也没成功起来

**Comment by TNT733** [comment]
补充一下，我用elastic-job 1.0.8也是如此，zookeeper jar包版本是3.4.6。请问是我哪里配置有误吗，谢谢

**Comment by TNT733** [comment]
后来已经解决。换了一个命名空间之后可以了，原来的那个命名空间在ZK中是一个文件，而不是文件夹，有点奇怪，不知为什么生成的是文件

**Comment by TNT733** [comment]
此问题已经找到原因并且可以重现，重现步骤：
1. 该namespace在客户端xml没有配置启动注册过
2. 启动elastic-job的console，直接添加该namespace
3. 再次启动客户端进程时，报
[Curator-Framework-0] [ZKPaths.java:76] [WARN ZKPaths] - The version of ZooKeeper being used doesn't support Container nodes. CreateMode.PERSISTENT will be used instead.
并且进程没有启动成功，一直block在这里

所以问题变成，被添加到console管理后台的namespace一定要先在客户端进程启动注册过了。这算不算一个bug呢？

**Comment by terrymanu** [comment]
请问这个目前的具体问题是什么？
”namespace一定要先在客户端进程启动注册过“这个没有看懂

**Comment by terrymanu** [comment]
长时间无回复，先关闭，有问题请再reopen

**Comment by lovepoem** [comment]
应该是curator-client 版本冲突的问题
