### ISSUE TITLE
springMVC 实现的web工程,在tomcat关闭时遇到定时任务线程关闭失败的问题

### ISSUE THREAD

**Issue by ZhangShufan15** [dangdangdotcom/elastic-job#113]
tomcat关闭的时候遇到定时任务线程关闭失败的问题，导致tomcat线程无法退出。

日志如下（和定时任务数量相同，以下是其中的一条）：
21-Jun-2016 17:03:32.764 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [nggirl] appears to have started a thread named [DEFAULT.MemDataLoadTask_Scheduler_QuartzSchedulerThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:410)

像是和quartz相关，[stackoverflow上的一个回复](http://stackoverflow.com/questions/7586255/quartz-memory-leak)

不确定，这是不是常规的解决方法。

是否有必要给JobRegistry添加开放的获取所有JobScheduleController的方法，同时给JobScheduleController开放isShutdown的方法？

**Comment by xiaoyaojc** [comment]
请问这个bug修复后的新版本什么时候发布呢？1.1.1也遇到了这个问题。

**Comment by terrymanu** [comment]
请优先阅读文档。文档中没有再提问。谢谢合作。
http://dangdangdotcom.github.io/elastic-job/post/release_notes/
