### ISSUE TITLE
容错性： 作业服务器和Zookeeper断开连接则立即停止作业运行

### ISSUE THREAD

**Issue by zman2013** [dangdangdotcom/elastic-job#114]
你好，

经测试发现与zookeeper断开连接的服务器上的任务没有立即停止运行，会将当前获得的分片对应的任务执行完成。

相应代码：
JobOperationListenerManager.jobScheduleController.pauseJob();

这样存在一个情况，如果使用了failover，当前服务器会继续执行完此分片。而另一个空闲服务器也获得了相同的分片，在同一时刻也执行相同的任务了。

谢谢

**Comment by hapic** [comment]
你好，请问这个bug修复了吗？我在测试时也遇到这样的问题

**Comment by terrymanu** [comment]
这个问题不太容易处理，如果立刻停止，则数据的完整性又可能会出现问题，都不是完善的解决方案。建议分布式的场景还是实现幂等性好些。
有什么更好的解决方案欢迎讨论。

**Comment by huangyiminghappy** [comment]
亮哥好，小弟个人建议：
1.最好是幂等性，不然重复执行很麻烦。
2.如果实在要解决，可能要设置一个job分片预估执行时间，根据上一次执行时间和预估该分片执行时间，等到了预估执行时间之后再重新分片

**Comment by terrymanu** [comment]
感谢建议。分片目前是按照作业触发时间做的。
增加分片预估时间就要增加使用的复杂度。
是否还有简单些的做法呢

**Comment by terrymanu** [comment]
长时间无反馈，先关闭了，有需要可以再reopen
