### ISSUE TITLE
是否可以支持自定义作业运行服务器标识

### ISSUE THREAD

**Issue by zhaolic39** [dangdangdotcom/elastic-job#117]
目前作业运行服务器是按照服务器IP注册和管理。

服务实例有时会部署在同一台服务器的不同端口上，此时就无法管理同一作业任务的不同运行实例。
是否能把获取服务器IP的方法抽象为获取服务器标识，可以让使用方自己提供获取服务器标识的实现。

**Comment by cherishniuniu** [comment]
支持，这样就可以在一个节点上跑多个了

**Comment by terrymanu** [comment]
在cloud版本可以实现此功能，未来的lite也会考虑实现，但目前暂时未排进计划

**Comment by terrymanu** [comment]
经过思考，觉得这个功能应属于部署系统。因此暂不考虑实现在elastic-job
