### ISSUE TITLE
spring容器关闭时，quartz未正常关闭

### ISSUE THREAD

**Issue by humnchou** [dangdangdotcom/elastic-job#119]
spring容器关闭时，没有处理quartz的正常关闭，导致项目无法正常关闭，日志如下：

[DEFAULT.simpleJob_Scheduler_QuartzSchedulerThread] but has failed to stop it. This is very likely to create a memory leak.

**Comment by terrymanu** [comment]
duplucate with #113

**Comment by everXu** [comment]
可以认领此任务？

**Comment by terrymanu** [comment]
欢迎认领，直接提交pull request即可
