### ISSUE TITLE
任务抛出运行时异常后，不会继续执行

### ISSUE THREAD

**Issue by kris1985** [dangdangdotcom/elastic-job#12]
你好，我在试用中发现了几个问题：

1、如果任务抛出运行时异常后，任务就不会再继续运行了。控制台也监控不了，状态一直是RUNNING。

2、job描述好像不支持中文

3、点击作业更新按钮没反应（chrome 最新版本）

4、控制台如果能看到作业的cron表达式就更好了

**Comment by terrymanu** [comment]
你好，关于后3个问题，应该是不存在的，请参见截图。
如果是更新按钮不起作用，可能是在某种条件下报错了，请查看chrome控制台，并将错误信息贴上来。
关于不支持中文这个问题多说一下，有的zk客户端不支持中文展现，如：ZooInspect。zk中存的都是byte数组，web console只是将其转为UTF-8编码的字符串。
第1个问题，我们之前做过测试，正常情况也不应有问题，应该还是控制台或作业后台报错导致，也请一并将错误日志贴上来吧，谢谢。
![image](https://cloud.githubusercontent.com/assets/5516298/10557109/fec9868a-74cf-11e5-96f1-cfa387cbf2b2.png)

**Comment by kris1985** [comment]
![Uploading QQ截图20151017162255.jpg…]()

作业显示和更新都有问题，所有字段显示为空。tomcat无错误日志


![Uploading 2.jpg…]()
job中抛出异常，相当于任务停止了。任务是没5秒执行一次，但执行一次就终止了。作业状态还是running

**Comment by kris1985** [comment]
![Uploading QQ截图20151017162255.jpg…]()

作业显示和更新都有问题，所有字段显示为空。tomcat无错误日志


![Uploading 2.jpg…]()
job中抛出异常，相当于任务停止了。任务是没5秒执行一次，但执行一次就终止了。作业状态还是running

**Comment by terrymanu** [comment]
明白了，应该是新增加了些作业的配置，老版本的作业没那些配置所以会报错。
请试试删除原有作业，重新运行，或者设置overwrite=true，允许新运行的作业覆盖原来的配置。
关于抛异常作业不运行的问题，请调好之前的问题再试试看看会不会发生
谢谢

**Comment by kris1985** [comment]
任务详情报错  路径：/job/settings?jobName=testJob

java.lang.NumberFormatException: null
	java.lang.Integer.parseInt(Integer.java:454)
	java.lang.Integer.parseInt(Integer.java:527)
	com.dangdang.ddframe.job.console.service.impl.JobDimensionServiceImpl.getJobSettings(JobDimensionServiceImpl.java:100)
	com.dangdang.ddframe.job.console.controller.JobController.getJobSettings(JobController.java:54)

在 JobDimensionServiceImpl 100行报了空指针
 result.setMaxTimeDiffSeconds(Integer.parseInt(curatorRepository.getData(JobNodePath.getConfigNodePath(jobName, "maxTimeDiffSeconds"))));

然而JobConfiguration 没有maxTimeDiffSeconds这个属性可以设置

另外删了所有作业、overwrite=true还是不行。抛异常后还是会终止任务。

**Comment by kris1985** [comment]
我知道了，应该是中央仓库没有更新，job-client 依赖的还是旧的。源码中JobConfiguration是有maxTimeDiffSeconds 这个字段的，默认是-1 不检查时间误差.

**Comment by kris1985** [comment]
控制台作业显示和更新问题解决了，但是更新cron表达式后，客户端作业好像没有实时更改。
由之前的0/5 * * * * ? 改成0/10 * * * * ?  后，还是每5s执行一次

**Comment by terrymanu** [comment]
可以连上zk看看cron是否修改成功了？

**Comment by terrymanu** [comment]
中央仓库将于1.0.2正式版再更新，目前snapshot先不更新

**Comment by kris1985** [comment]
![1](https://cloud.githubusercontent.com/assets/4971830/10559687/96fbf4ca-7529-11e5-96ca-2f7df09e2430.jpg)

zk上已经修改成功，但是认为还是没5s执行一次

------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:05 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:10 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:15 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:20 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:25 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:30 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:35 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:40 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:45 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:50 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:51:55 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:52:00 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:52:05 --------testJob
------ OneOffElasticDemoJob process: [0] at 2015-10-17 23:52:10 --------testJob

能加你Q吗？

**Comment by terrymanu** [comment]
可以加首页的qq群，加我qq也行，2565428530，不过技术讨论最好在群里，帮忙的人也能多些
