### ISSUE TITLE
dataflow类型的定时任务无法失效转移

### ISSUE THREAD

**Issue by 785129039** [dangdangdotcom/elastic-job#121]
请问: elastic-job dataflow类型的定时任务无法失效转移吗，我设置了failover="true"，测试结果是无法失效转移的。但是simple类型的任务就可以失效转移。

test无法失效转移， test2可以失效转移

![catch 07-25-08-30-38](https://cloud.githubusercontent.com/assets/4322248/17087755/db61c160-5243-11e6-99fa-f6717eca3e90.jpg)

thank you!

**Comment by terrymanu** [comment]
失效转移是都支持的。如果使用有问题，请提供更加详细的信息，比如：代码，日志，dump等信息，并在qq群讨论。

**Comment by 785129039** [comment]
嗯，我根据和example对比，测试发现是test添加的 listener 设置了started-timeout-milliseconds 和 completed-timeout-milliseconds为0导致的，看文档解析为 最后一个作业执行前/后的执行方法的超时时间， 但是还是没有理解到底指的哪个方法，能解释一下吗？ 谢谢
