### ISSUE TITLE
多个进程部署一样的代码，只希望一个进程执行定时任务

### ISSUE THREAD

**Issue by dragontree101** [dangdangdotcom/elastic-job#124]
目前就只把shardingCount参数设置成1，并且实现了AbstractDistributeOnceElasticJobListener类，但是启动两个进程的时候， 两个进程都还是会执行任务代码。目前使用的版本1.1.0。

请问如何配置能够使得在同样的代码里面仅仅一个进程实例执行定时任务， 谢谢！

**Comment by dragontree101** [comment]
我发现如果我两个进程部署在一个机器上面，  两个进程都会进行执行任务， 但是如果两个进程部署到不同的机器上面， 就只会有一个进程执行任务。  我觉得任务不应该以机器来进行单位的分割， 而是应该以进程进行单位的分割

**Comment by yuck0419** [comment]
elastic job不是以进程来区分的，是以IP来区分的，在文档里有说。同一个IP可能会被认为是同一个实例，所以就都触发了任务。

**Comment by dragontree101** [comment]
恩， 了解了，谢谢， 我觉得应该是以进程更加合理， 如果以ip进行区分， 不利于本地测试。

**Comment by terrymanu** [comment]
目前lite版仍是针对ip分片，如果不针对ip分片，建议2.0稳定后尝试cloud版本
