### ISSUE TITLE
当Cron表达式是某个时间点第一次触发完成后，在Console里面重新调整表达式，任务报错

### ISSUE THREAD

**Issue by lzw2006** [dangdangdotcom/elastic-job#125]
例如我的Cron表达式是30 17 17 30 08 ? 2016(2016-08-30 17:17:30)，当正常执行完这个任务后，我想调整下一次执行的时间，于是把Cron表达式改为30 20 20 30 08 ? 2016，当到达这个时间点后，作业报错
Caused by: org.quartz.JobPersistenceException: The job (DEFAULT.mergeDataForLongTime) referenced by the trigger does not exist.

**Comment by ZhangShufan15** [comment]
可以贴一下你调用的代码段，我们you这样用的地方，没有出现这个问题

**Comment by terrymanu** [comment]
长时间未更新，且并未重现，先关闭了，有问题请reopen

**Comment by xiaojianyu315** [comment]
@terrymanu 
![wechatimg234](https://user-images.githubusercontent.com/16017664/39304208-894ccf46-498b-11e8-881e-3f2bef4c0b02.jpeg)
我也遇到了同样的问题

**Comment by xiaojianyu315** [comment]
@lzw2006 你的问题解决了吗？
