### ISSUE TITLE
zookeeper集群怎么运行分布式任务,能给一个详细点的分布式任务文档吗

### ISSUE THREAD

**Issue by 205140040** [dangdangdotcom/elastic-job#133]
zookeeper集群怎么运行分布式任务,能给一个详细点的分布式任务文档吗

**Comment by kaybinwong** [comment]
同一注册中心，多个机器启动同一作业即可，不关zookeeper集群的事。

**Comment by terrymanu** [comment]
请阅读文档，example并尝试理解elastic-job的理念，这些文档中都包含，请不要在issue中涉及初级问题，谢谢合作。
