### ISSUE TITLE
job_trace_log表是记录什么的？执行job之后，在控制台操作job的暂停启动，这张表一直是空的

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#135]
![image](https://cloud.githubusercontent.com/assets/9999969/18626391/5bc51fea-7e87-11e6-9813-d947386763d2.png)

**Comment by workcheng** [comment]
![image](https://cloud.githubusercontent.com/assets/9999969/18734202/8a662622-80a4-11e6-963d-20e05ca5c94c.png)
希望完善一下这方面相关的文档

**Comment by terrymanu** [comment]
我们近期会更新文档，谢谢提醒

**Comment by terrymanu** [comment]
文档已更新，请参考：http://dangdangdotcom.github.io/elastic-job/post/user_guide/common/event_trace/
