### ISSUE TITLE
作业分片执行，怎么理解？

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#136]
是不是我在多个服务器上部署同样的调度任务包去执行它，e-job会把这些任务分片，按照作业分片策略把这些任务分派到这些服务器上分片执行，以达到最大化的利用资源，快速执行任务的目的，是这样理解吗？希望完善一下这方面的Wiki，谢谢！

**Comment by terrymanu** [comment]
请仔细阅读文档，首页就有写
