### ISSUE TITLE
console里面对作业进行“关闭”操作之后，如何让作业再次启动？

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#137]
在控制台中对正在进行的作业，点击关闭之后，只剩下触发和删除操作按钮，点击触发按钮没反应，点击删除操作可以正常起作用，请问“关闭”操作之后，如何让作业任务再次的启动？点击关闭按钮之后，留下的触发按钮的作用是什么？

**Comment by terrymanu** [comment]
并不能通过控制台再次启动作业。请阅读文档并理解elastic-job-lite的理念，这些文档中都包含
