### ISSUE TITLE
elastic-job 2.0.0-SNAPSHOT版本 启动时找不到对应的job

### ISSUE THREAD

**Issue by xiaoyaojc** [dangdangdotcom/elastic-job#140]
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /yibao-job.
yibao-job是作业注册中心配置的namespace，相同的配置在1.1.1版本中可正常运行，但是用Elastic-Job-Lite 2.0.0-SNAPSHOT 版本就会出现上述问题。
zk版本为zookeeper-3.5.1-alpha。

**Comment by terrymanu** [comment]
请提供更加详细的重现步骤

**Comment by terrymanu** [comment]
长时间未反馈，问题关闭
