### ISSUE TITLE
elastic-job无法加载占位符实现远程加载配置。

### ISSUE THREAD

**Issue by 843257317** [dangdangdotcom/elastic-job#141]
通过“org.springframework.beans.factory.config.PropertyPlaceholderConfigurer”  实现远程加载占位符 “${}” 配置，发现elastic-job的 serverList 属性（zk地址），用占位符无法获取。其他的如dubbo都是正常的。

**Comment by 843257317** [comment]
我们在项目中用了xxl-conf类似config-tool的工具，希望远程获取配置信息，所有的配置均可以取到唯独elastic-job的配置无法获取。本来elastic-job是独立的spring xml配置文件，为了排除加载不到或者是加载顺序问题，将配置信息挪到dobbo的spring文件里，依然获取不到。将该值写死在serverList 里是ok的

**Comment by yangl** [comment]
试下把elastic-job相关的配置移到context:property-placeholder所在的文件里哈

**Comment by terrymanu** [comment]
elastic-job并不需要加载远程配置。
加载远程配置是注册中心的功能。
近期elastic-job会把从zk加载文件到placeholder的功能去掉
