### ISSUE TITLE
是否能够支持fixed-delay，而不是cron的表达式

### ISSUE THREAD

**Issue by dragontree101** [dangdangdotcom/elastic-job#144]
我想问问 elasticjob是不是可以支持 fixed-deley的形式，比如就是固定延迟20s，这类的， 而不是一个crontab的表达式的形式？

**Comment by dragontree101** [comment]
是不是 不能进行支持呢？  麻烦@terrymanu 解答一下，谢谢

**Comment by terrymanu** [comment]
目前暂时不支持，我们内部用cron足够了。这个需求优先级比较低

**Comment by dragontree101** [comment]
好的， 知道了， 谢谢
