### ISSUE TITLE
console作业维度加载不出来 后台有报空指针错误。

### ISSUE THREAD

**Issue by blackcat1991** [dangdangdotcom/elastic-job#147]
跟踪代码在这里获取liteJobConfig的时候为null导致后面的空指针错误。
LiteJobConfiguration liteJobConfig = LiteJobConfigurationGsonFactory.fromJson(regCenter.get(jobNodePath.getConfigNodePath()));

jobBriefInfo.setJobType(liteJobConfig.getTypeConfig().getJobType().name());

**Comment by workcheng** [comment]
我也遇到了这个问题，我登陆zookeeper之后，看到一个config节点不正常，我看到那个作业已经不再用了，就把那个错误的作业节点直接手动删除了，然后在刷新一下运维平台就可以了。这个是那个错误的节点：
![default](https://cloud.githubusercontent.com/assets/9999969/19800915/916ff18a-9d2f-11e6-9259-9eabd2d4ad73.png)，
删除之后：
![image](https://cloud.githubusercontent.com/assets/9999969/19800966/bc2811fa-9d2f-11e6-8c12-8862520a59c9.png)
