### ISSUE TITLE
运维平台删除作业，偶尔会遇到删除不全的情况

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#149]
![image](https://cloud.githubusercontent.com/assets/9999969/19846422/16d56142-9f7a-11e6-91c8-31b97eec02a0.png)

![image](https://cloud.githubusercontent.com/assets/9999969/19846529/1353024e-9f7b-11e6-9e12-100084a63ed5.png)
在运维平台 作业服务器一栏上，点击删除，偶尔会出现没有删除完全的情况，如图索引匹配服务的config只剩下leader节点，从而导致了bug#147的产生，只能手动删除这个节点,或者重新运行这个作业来解决

**Comment by terrymanu** [comment]
应该是leader节点在选举导致。并不是没有删掉，而是删掉之后又选举，重新写的。
这个问题我们再看一下，需要删除时停止选举

**Comment by johnyannj** [comment]
没修正 为什么关闭了？
