### ISSUE TITLE
Elastic-Job事件追踪-基于关系型数据库的事件追踪不支持oracle数据库

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#151]
建表语句不兼容，导致事件追踪记录报错

**Comment by terrymanu** [comment]
目前仅支持mysql，以后会做建表语句可配置

**Comment by yuweiming2016** [comment]
同问，现在还不支持呢，有计划吗？

![image](https://user-images.githubusercontent.com/22490427/33862365-4de7d050-df1d-11e7-8427-919571522ce8.png)
