### ISSUE TITLE
脚本作业的脚本执行路径更改成功，但是触发作业执行的依然是上一次的脚本作业路径

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#154]
1.我运行一个脚本作业，是一个在window下执行一个bat脚本，触发一个发送邮件的接口，在运维平台触发，邮件发送成功；
2.然后在运维平台更改该作业的 脚本作业全路径 为一个打开网页的脚本的路径，运维平台更新成功，查看zookeeper注册中心config也显示更新成功，再次触发执行该脚本作业，触发的作业依然是发送邮件的脚本

**Comment by haocao** [comment]
2.0.1版本并未重现，请再检查一下环境及相关配置。

**Comment by workcheng** [comment]
嗯，确实是，我刚刚用2.0.0版本验证了一下确实没出现，我是在2.0.0预览版发现这个问题的

**Comment by workcheng** [comment]
这个问题在2.0.1版本上又出现了，我今天在测试环境下调试的时候出现了，好像跟运维平台有关，运维平台运行久了就会出现这个问题

**Comment by terrymanu** [comment]
长时间无反馈，先关闭了。如仍然有问题，请提供详细的重现条件以及dump数据。
