### ISSUE TITLE
任务设置disable＝true后，启动项目还是会自动执行任务

### ISSUE THREAD

**Issue by sunnyxd** [dangdangdotcom/elastic-job#163]
已检查zookeeper config中的配置， 也是disable＝true，但是启动项目还是会自动执行任务

**Comment by terrymanu** [comment]
没有重现，请问有其他细节可以帮助重现么

**Comment by terrymanu** [comment]
原overwrite和disable的配置有关系，只有配置了overwrite=true，disable才会改变原有状态。
disable是启动时状态，与disable和overwrite无关。overwrite只负责配置是否覆盖注册中心。

**Comment by lengfo** [comment]
这个问题解决了吗？ 我2.0.3  ，2.0.4master 版本还是有这个问题呢?

**Comment by haocao** [comment]
已经在2.0.4-SNAPSHOT版本修复，请知悉。
