### ISSUE TITLE
console中一台暂停，作业运行状态为disable

### ISSUE THREAD

**Issue by CrossChan** [dangdangdotcom/elastic-job#169]
版本是2.0.2-snapshot
步骤：
1、将1个作业分成3片，2台服务器运行，这期间作业状态都是正常的
2、将其中一台服务器暂停操作，此时作业状态为disable（是否应该是部分失效），但是没有暂停的机器重新分片后，正常运行
![q](https://cloud.githubusercontent.com/assets/5645103/20338749/e69906ae-ac13-11e6-976a-84017797d26f.jpg)
![a](https://cloud.githubusercontent.com/assets/5645103/20338754/ea2f1524-ac13-11e6-8efa-a693fef56064.jpg)

**Comment by terrymanu** [comment]
请把操作步骤，操作之前的状态描述清楚，并提供zk的dump信息，谢谢

**Comment by CrossChan** [comment]
2台机器的dump信息如下：
![z](https://cloud.githubusercontent.com/assets/5645103/20338772/07da4e54-ac14-11e6-8c2c-c3f5e311a554.jpg)
![x](https://cloud.githubusercontent.com/assets/5645103/20338773/09be3d02-ac14-11e6-9aac-d985fc5bfa46.jpg)

**Comment by CrossChan** [comment]
这个好像不是必现，偶尔会出现这种情况

**Comment by terrymanu** [comment]
请问这个dump信息是有问题还是没问题的，我看到的是一台暂停，一台运行。能配合信息把场景和步骤说清楚么

**Comment by CrossChan** [comment]
dump是没问题的，就是在一台暂停，一台运行的情况下，作业总览中的该状态是disabled，这个disabled状态是不是在此时是有问题的

**Comment by terrymanu** [comment]
请提供重现条件，以及和当时错误状态有关的dump信息。这样的信息不足以让我们重现问题

**Comment by terrymanu** [comment]
请问问题解决了么？关掉issue的原因是什么
