### ISSUE TITLE
cloud job成功执行，任务执行中无状态反馈，结束后仅获得TASK_FAILED

### ISSUE THREAD

**Issue by crabo** [dangdangdotcom/elastic-job#176]
设置了一个sleep 30s的python脚本，tar.gz 打包在http服务器。
 使用原生python mesos测试正常log如下：（有TASK_RUNNING状态）
I1122 16:43:09.494536 27891 slave.cpp:1987] Queued task '0' for executor '0' of framework TEST_FRAMEWORK
I1122 16:43:09.494546 27892 containerizer.cpp:938] Starting container 001 for executor '0' of framework TEST_FRAMEWORK
I1122 16:43:09.495591 27892 linux_launcher.cpp:421] Launching container 001 and cloning with namespaces 
I1122 16:43:09.497591 27892 systemd.cpp:96] Assigned child process '10106' to 'mesos_executors.slice'
I1122 16:43:09.627706 27894 slave.cpp:3231] Got registration for executor '0' of framework TEST_FRAMEWORK from executor(1)@127.0.0.1:34071
I1122 16:43:09.628365 27891 slave.cpp:2191] Sending queued task '0' to executor '0' of framework TEST_FRAMEWORK at executor(1)@127.0.0.1:34071
I1122 16:43:09.636193 27894 slave.cpp:3634] Handling status update TASK_RUNNING for task 0 of framework TEST_FRAMEWORK from executor(1)@127.0.0.1:34071
I1122 16:43:09.636636 27895 status_update_manager.cpp:323] Received status update TASK_RUNNINGfor task 0 of framework TEST_FRAMEWORK
I1122 16:43:09.636848 27895 slave.cpp:4051] Forwarding the update TASK_RUNNING for task 0 of framework TEST_FRAMEWORK to master@127.0.0.1:5050
I1122 16:43:09.636962 27895 slave.cpp:3961] Sending acknowledgement for status update TASK_RUNNING for task 0 of framework TEST_FRAMEWORK to executor(1)@127.0.0.1:34071
I1122 16:43:09.639317 27894 status_update_manager.cpp:395] Received status update acknowledgement for task 0 of framework TEST_FRAMEWORK
I1122 16:43:39.762295 27896 slave.cpp:3634] Handling status update TASK_FINISHED for task 0 of framework TEST_FRAMEWORK from executor(1)@127.0.0.1:34071

使用scheduler 提交执行：（仅TASK_FAILED 状态）
I1122 16:23:49.930668 19333 slave.cpp:1539] Got assigned task 'TEST_JOB' for framework TEST_FRAMEWORK
I1122 16:23:49.931025 19333 slave.cpp:1701] Launching task 'TEST_JOB' for framework TEST_FRAMEWORK
I1122 16:23:49.938344 19333 slave.cpp:6179] Launching executor '..' of framework TEST_FRAMEWORK with resources cpus(*):0.1; mem(*):64 in work directory '/var/lib/mesos/slaves/..'
I1122 16:23:49.938719 19335 containerizer.cpp:938] Starting container 001 for executor 'S0' of framework TEST_FRAMEWORK
I1122 16:23:49.938753 19333 slave.cpp:1987] Queued task 'TEST_JOB' for executor 'S0' of framework TEST_FRAMEWORK
I1122 16:23:49.955579 19327 linux_launcher.cpp:421] Launching container 001 and cloning with namespaces 
I1122 16:23:49.960724 19327 systemd.cpp:96] Assigned child process '19465' to 'mesos_executors.slice'
I1122 16:24:20.368683 19331 containerizer.cpp:2313] Container 001 has exited
I1122 16:24:20.368778 19331 containerizer.cpp:1950] Destroying container 001 in RUNNING state
I1122 16:24:20.368945 19331 linux_launcher.cpp:498] Asked to destroy container 001
I1122 16:24:20.390444 19330 slave.cpp:4542] Executor 'S0' of framework TEST_FRAMEWORK exited with status 0
I1122 16:24:20.392068 19330 slave.cpp:3634] Handling status update TASK_FAILED for task TEST_JOB of framework TEST_FRAMEWORK from @0.0.0.0:0

**Comment by terrymanu** [comment]
能把tar.gz在群里传一下么，是不是打包有问题

**Comment by crabo** [comment]
我还没加群。  从slave的stdout 可以看见成功解包， 成功执行（上述log也能发现都有30秒间隔）。
打开tracelog表是3条记录， TASK_STAGING => TASK_FAILED(Executor terminated)=>TASK_KILLED(Unregistered executor)

用python的mesos提交同一个uri， 任务执行log有RUNNING。我测试打包zip，效果完全一样。
文件是这个： http://yzh.southinfo.net:8080/ping.zip   bootstrap="python bin/ping.py"

**Comment by terrymanu** [comment]
目前来看，用于运行的作业jar不正确。请调整一下。如有进一步问题，请reopen继续沟通

**Comment by terrymanu** [comment]
duplicate with #179
