### ISSUE TITLE
2.0.2版本里面Zookeeper异步连接有问题

### ISSUE THREAD

**Issue by soiff** [dangdangdotcom/elastic-job#180]
`ZookeeperRegistryCenter#init`第100行、101行，这里实际上采用的异步方式发起连接，但在本机（4核8线程）上测试时发现，`ConnectionStateManager`状态改变后立刻返回，几乎不可能出现线程切换，在101行对客户端连接状态的判断实际上取得仍然是未连接状态。既然是初始化，这里为何要采用异步连接？既然是异步连接为何在返回后立刻取值判断？线程没有切换之前，获取的值肯定是未连接状态。这里的处理逻辑是否有问题还请看看！

**Comment by terrymanu** [comment]
是的，我们也希望使用sync的方式start curator，但是没有发现合适的方法。请问你有什么解决方案可以同步启动curator的client么？

**Comment by soiff** [comment]
是否可以考虑忽略返回值，不要去检查是否已连接，没有连接的话将无法正常工作，检查一下日志就可以确定问题所在了。不一定非要通过技术手段解决这种业务问题嘛！

**Comment by terrymanu** [comment]
这是不行的。esjob会在init后马上进行zk的读写操作。如果不能确保链接成功，正常的读写操作就会受影响。你可以注释掉那块代码试试，esjob应该根本无法启动。

**Comment by soiff** [comment]
实际上是把问题暴露给运维，不过现有这种写法本身不太合理呀，与其不能达到连接状态检查效果，不如把问题暴露给运维人员。

**Comment by soiff** [comment]
阻塞还是要要的，只不过不去检查是否连接成功，成功了自然能起来，失败了不过就是起不来嘛！反正检查不通过也是一样的不能用。

**Comment by terrymanu** [comment]
可能你没有理解我的意思，只要你注释掉那段代码就知道了。根本就不能运行，不是暴露不暴露给运维的问题。而是及时zk正常可用，esjob也不可用。因为start之后如果不block，程序就继续向下走了，而这时链接是不可用的，但esjob会马上获取zk数据。
简单说，即使zk可用，不block也会出异常，并不是不可用的意外状况。

**Comment by terrymanu** [comment]
先在的情况是timeout之后会抛异常的

**Comment by soiff** [comment]
我的本意是说，阻塞还是应该阻塞，只不过我们不判断client的连接状态，这种情况下如果连接成功返回，esjob仍然会启动失败么？

**Comment by terrymanu** [comment]
这取决于zk的网速。如果block到超时时间之后，zk仍然没有连上，直接抛异常是否比之后使用时抛异常更好些，所谓的failfast是否更清晰呢

**Comment by soiff** [comment]
我认为如果希望实现failfast其实很简单，我们只需要检测阻塞返回结果：

    final boolean isConnected = client.blockUntilConnected(zkConfig.getMaxSleepTimeMilliseconds() * zkConfig.getMaxRetries(), TimeUnit.MILLISECONDS);
    if (! isConnected) {
        client.close();
        throw new KeeperException.OperationTimeoutException();
    }

`curator-framework:2.10.0`中提供的方法`blockUntilConnected`实际上返回值已经说明问题了，这本身是个同步方法（内部通过异步方式实现），返回为真表示已成功连接，否则表示连接失败（如超时）。

**Comment by terrymanu** [comment]
好的，谢谢建议。我们改一下，确实代码要清爽一点

**Comment by soiff** [comment]
好的，感谢！我们目前同时在考虑多个任务调度框架，esjob比较符合我们的需求，这个问题在做本地测试时发现的，也不是什么严重的问题！

**Comment by Debenson** [comment]
这个问题我们也经常遇到，以前只能增加连接时间来解决：
    sessionTimeoutMilliseconds: 600000
    connectionTimeoutMilliseconds: 600000
    baseSleepTimeMilliseconds: 10000
    maxSleepTimeMilliseconds: 30000
    max-retries: 10

后来网上有篇文章，解决这个疑问: 
https://blog.csdn.net/weixin_39633245/article/details/127754442

简单点的解决方案:
 -Dzookeeper.sasl.client=false
加上后，连接立即就成功了， 不用再修改连接超时时间

**Comment by huaihuailj** [comment]
您好，我已收到您的邮件，我会尽快回复~
