### ISSUE TITLE
elastic-job-lite-console在docker容器中运行不能正常显示job信息

### ISSUE THREAD

**Issue by soiff** [dangdangdotcom/elastic-job#183]
直接基于tomcat:8.0.39-jre8将console的war包加入到docker镜像，启动后添加zookeeper能连接成功，但该注册中心下的任务详情却无法看到：

![image](https://cloud.githubusercontent.com/assets/13597105/20698813/898963f2-b63e-11e6-9cc2-67fcffca8085.png)

    $ docker ps
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                          NAMES
    2eb7bae9e738        esjob:1.0           "java -jar /opt/examp"   23 minutes ago      Up 23     minutes                                      esjob.1.by5wobktyzjijl1xz22c1xf8d
    533b3804e52a        esjob-console:1.0   "catalina.sh run"        24 minutes ago      Up 23 minutes       8080/    tcp                       esjob-console.1.dqm68eg1sxzwpqa3laoijoesq
    fc02935866a5        zookeeper:latest    "/docker-entrypoint.s"   51 minutes ago      Up 51 minutes       2181/tcp, 2888/    tcp, 3888/tcp   zookeeper.1.7insix3qzr6yhjnm38qxg5k9e

请问可能是什么原因呢？是不是还需要暴露额外的端口？不过看README文档中并无额外端口说明。

**Comment by soiff** [comment]
另外，这里esjob容器可以接收到调度任务并处理:

    2016-11-29 05:50:45.172  INFO 1 --- [           main] c.d.e.elastic.job.ElasticJobApplication  : Started     ElasticJobApplication in 2.073 seconds (JVM running for 2.384)
    2016-11-29 06:00:52.171  INFO 1 --- [ed-job_Worker-1] c.d.examples.elastic.job.ExampleJob      : Time: Tue Nov 29 06:00:52 UTC 2016, Count: 1

最后一条日志就是esjob处理任务时打印出来的日志。

**Comment by terrymanu** [comment]
作业运行正常么，作业是docker还是实体机。
我想到的问题有两个：
1. tomcat 8没试过，可以看看不用docker直接放tomcat8有无问题
2. esjob-console会读取用户目录下.elastic-job-console下的xml文件，不知道这个目录在docker下是否有问题

**Comment by soiff** [comment]
作业也是运行在docker中，初步看作业运行是正常的，之前console直接放在tomcat 8下面也是没有问题的。我进入esjob-console的容器内检查了配置文件，内容如下：

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <registryCenterConfigurations>
        <registryCenterConfiguration name="10.80.1.142:2181" zkAddressList="10.80.1.142:2181" namespace="" digest=""     activated="true"/>
    </registryCenterConfigurations>

看起来好像没什么问题，我准备调试一下，确认是否是由于该文件读取导致。

**Comment by soiff** [comment]
根据调试信息来看，注册中心的读取加载、解析貌似没什么问题：

![image](https://cloud.githubusercontent.com/assets/13597105/20700417/45bd6510-b648-11e6-9ffe-355a4522915d.png)

**Comment by soiff** [comment]
![image](https://cloud.githubusercontent.com/assets/13597105/20700429/56196788-b648-11e6-8a3f-d276679aea21.png)

**Comment by soiff** [comment]
抱歉，问题确认是因为命名空间导致，我增加的注册中心未指定namespace，但esjob携带了命名空间。
