### ISSUE TITLE
管理后台执行失效操作，但任务还在执行

### ISSUE THREAD

**Issue by chenfeng1985** [dangdangdotcom/elastic-job#189]
elastic-job-lite-console 版本：2.0.3
操作前状态：运行状态
现象：在管理后台点击“失效”按钮，前台返回操作成功，但是后台任务还在执行，已确认和任务逻辑无关，Job里面什么逻辑都不写也是一样。

**Comment by lengfo** [comment]
遇到同样的问题，我是用代码创建的JOB ，不是spring 配置
` // 定义Lite作业根配置
        LiteJobConfiguration liteJobConfiguration = LiteJobConfiguration.newBuilder(jobConfiguration)
                .overwrite(true)
                .disabled(true)
                .monitorExecution(false)
                .build();`

部署后，即使disabled ，任务也会自动执行，必须shutdown任务才能停止。
