### ISSUE TITLE
本地作业执行过快，日志数据库可能监控不到数据 

### ISSUE THREAD

**Issue by dhb52cat** [dangdangdotcom/elastic-job#192]
JobEventRdbStorage boolean addJobExecutionEvent(final JobExecutionEvent jobExecutionEvent) {
    	System.out.println(jobExecutionEvent.getCompleteTime());
        boolean result = false;
        if (null == jobExecutionEvent.getCompleteTime()) {    这里的判空经常在插入前就有值了

**Comment by terrymanu** [comment]
dup with #204
