### ISSUE TITLE
单进程内多个任务突然有一个停止运行了

### ISSUE THREAD

**Issue by nisiyong** [dangdangdotcom/elastic-job#193]
项目刚开始用elastic-job不久，选择的是1.1.1版本，现在没有用到分布式作业，即每个job的分片都为1，进程要是挂了有脚本重启进程。虽然现在做法比较low，可以用到elastic-job更多功能，但是暂时能满足我们的需求。

生产环境有12个进程，平均每个进程有4个任务，刚开始一切运行良好。后来收到反馈说有些任务停止了，查了一下进程没有挂，所有状态也都是READY，而且该进程的其他任务都正常运行，只有一个停止跑了，在控制台点触发也没有用。没有错误日志，重启后就正常了。其他进程也出现过这种情况，到目前为止有3次了，好难定位问题的原因。

**Comment by terrymanu** [comment]
1.x版本已不维护，请升级2.x
