### ISSUE TITLE
elastic-job-lite：主节点增加reconcile线程任务，修复分片不一致等分布式相关一致性问题。

### ISSUE THREAD

**Issue by terrymanu** [dangdangdotcom/elastic-job#195]
1. 启动另一线程，检查已停止的作业仍然包含分片的情况，设置resharding标记 
2. 配置检查线程的间隔时间，在config，spring命名空间和webconsole中增加配置 
3. 提炼出异常检测框架，可快速合理的增加新的异常检测规则

**Comment by fushun620** [comment]
承接任务
