### ISSUE TITLE
2.0版本中, 为什么设计一个job对应一个Quartz Scheduler?

### ISSUE THREAD

**Issue by yzhang226** [dangdangdotcom/elastic-job#196]
2.0版本中, 为什么设计一个job对应一个Quartz Scheduler?

谢谢

**Comment by terrymanu** [comment]
就是这么设计的。如果觉得有问题可以讨论下如何设计更好些

**Comment by terrymanu** [comment]
长时间无反馈，先关闭，有需要请再reopen

**Comment by yzhang226** [comment]
真是不好意思，以后有想法再打开

**Comment by xin497668869** [comment]
如果是一个schedule实例对应多个线程, 多个trigger占用的资源会不会更少一点, 毕竟只有一个线程在while, 用线程池的方式去执行任务. 如果定时任务多且能接受一些延迟, 就能批量执行定时任务, 效率还是挺高的

**Comment by xin497668869** [comment]
目前ej是基于quartz的ram去存储任务, 再在上层进行一个调度分片. 想了下还有另一种方案是自定义一个jobstore代替ram和数据库锁, 用数据库或者redis去存定时任务, zookeeper做调度和分片.quartz本来就是一个很灵活的框架, 感觉这种对quartz封装比较少, 可配置的参数也比较多.

**Comment by terrymanu** [comment]
单实例多线程会导致作业触发时产生多实例，难于控制分布式条件下每个分片仅执行一次

**Comment by terrymanu** [comment]
使用其他的jobStore也是一种方案。不过对quartz的依赖太大了。ejob想做一个分布式调度的标准，而不仅仅是quartz的插件，因此就采用了现在这种方式。未来的ejob去掉quartz也不是没有可能。就好像sharding-jdbc去掉对druid依赖一样。希望ejob可以尽量减少依赖，提供更轻量级的应用。

**Comment by xin497668869** [comment]
如果是在jobStore那里分片会比较麻烦.  那里分任务比较合适.  少量大任务分片比较合适, 大量小任务服务器分任务触发会更合适些.

**Comment by xin497668869** [comment]
请教一下, 每个实例也是也线程, 其实也是一样的, 为什么说难以控制分片仅执行一次呢?

**Comment by xin497668869** [comment]
如果是用jobStore的话, 那里分片会比较麻烦. 那里分任务比较合适. 少量大任务分片比较合适, 大量小任务服务器分任务触发会更合适些.

**Comment by xin497668869** [comment]
@terrymanu

**Comment by terrymanu** [comment]
因为以后有可能直接去掉quartz，在jobStore扩展只会和quartz绑得更紧

**Comment by xin497668869** [comment]
嗯, 不在jobStore拓展这个明白.  那个实例和线程的问题呢? 还是不是太明白为什么单实例多线程会难以控制分片呢? @terrymanu

**Comment by terrymanu** [comment]
我记得应该是，单线程才能保证每个作业是串行执行。如果多作业公用一个线程池，同一个作业不一定是串行的，有线程资源即会执行，会导致上次执行未结束，下次触发再开始时，有线程资源即会执行。
不过这里确实没测试过。如果不是这样可以继续讨论

**Comment by xin497668869** [comment]
看了下源码, 在RAMJobStore的acquireNextTriggers方法里面有处理, 可以用@DisallowConcurrentExecution标注类, 就能串行了, 不会有多个实例同时执行的问题 @terrymanu

**Comment by xin497668869** [comment]
@terrymanu
