### ISSUE TITLE
job-lite ，有分片处理失败时能自动迁移吗？

### ISSUE THREAD

**Issue by Ah39** [dangdangdotcom/elastic-job#197]
比如分片1，2，3在A，B，C三台机器上运行，A上的1失败了，能自动迁移到B或者C上吗？
还有一个问题，Script类型的作业，不能引用lite的jar包吧？Script 类型的作业怎么注册到注册中心，怎么做故障迁移？？

**Comment by terrymanu** [comment]
都是可以的。原理问题就不做过多解释了，请看源码
