### ISSUE TITLE
job-lite script作业

### ISSUE THREAD

**Issue by Ah39** [dangdangdotcom/elastic-job#198]
Script类型作业
Script类型作业意为脚本类型作业，支持shell，python，perl等所有类型脚本。只需通过控制台或代码配置scriptCommandLine即可，无需编码。执行脚本路径可包含参数，参数传递完毕后，作业框架会自动追加最后一个参数为作业运行时信息。
Script类型作业，不是java项目，纯粹的python工程，怎么实现注册，和分片等？？

**Comment by terrymanu** [comment]
都可以做到，原理问题请看源码，恕难以在每个issue中解释
