### ISSUE TITLE
注册中心支持多个namespace吗？

### ISSUE THREAD

**Issue by linbo** [dangdangdotcom/elastic-job#199]
请问一下，用zookeeper做注册中心，支持同一个zookeeper集群注册多个namespace吗？

例如：

<reg:zookeeper id="regCenter1" server-lists="yourhost:2181" namespace="**dd-job1**" base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3" />
    <reg:zookeeper id="regCenter2" server-lists="yourhost:2181" namespace="**dd-job2**" base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3" />

**Comment by yysct2005** [comment]
这个问题怎么关闭了？有答案么？
