### ISSUE TITLE
[功能提升] 增加前置和后置任务

### ISSUE THREAD

**Issue by cjdxhjj** [dangdangdotcom/elastic-job#2]
有些任务，比如系统间定期数据同步，需要将已有数据清空，然后将新数据导入到系统中，并且前置任务只执行一次（执行前j环境准备）。目前没有相关方法做此工作，建议在任务执行主节点进行任务分配之前或之后由主节点执行相应回调，如init.

**Comment by terrymanu** [comment]
由于各个任务是分布式的，由于各个服务器有时间差，无法保证主节点一定最先执行。
如果从节点先于主节点执行，会发生init方法还没有执行的问题，从节点作业就运行的问题。
改为主节点不执行，其他节点阻塞，有2个问题：
1. 吞吐量下降
2. 如何判断主节点在本次作业中是否执行过。因为作业循环往复，本次执行结束和下次执行开始在分布式环境下无法区分

欢迎讨论，
如果可以有方法实现让主节点一定优先于从节点执行的方法，这个issue才可以继续做。

**Comment by joock** [comment]
在后置任务中指定前置任务，前置任务完成之后，在zk中记录一条信息，对应的后置任务到达执行时间的时候，去前置任务写信息的zk节点读取一下信息（与框架无关，应用自行写入），看符合条件的前置任务是否运行完毕。

**Comment by gl2001wl** [comment]
任务依赖，之前使用quartz自己的listener实现的，前置自动触发后置的
