### ISSUE TITLE
部署3台机子出现内存泄漏的问题

### ISSUE THREAD

**Issue by ljz0721cx** [dangdangdotcom/elastic-job#2]
在使用的时候java.util.concurrent.Executors$RunnableAdapter 
![image](https://user-images.githubusercontent.com/4934976/34398498-5275913a-ebba-11e7-8d3c-4a6f5954f80d.png)
对应的dump文件比较大，主要是以下这些dui对象发生的泄漏
![image](https://user-images.githubusercontent.com/4934976/34398516-7b33385c-ebba-11e7-8006-20d86f2ff150.png)

使用的版本号为
elastic-job-core 1.1.1
elastic-job-spring  1.1.1
elastic-job-api-core  1.1.1

**Comment by terrymanu** [comment]
请提供版本号

**Comment by ljz0721cx** [comment]
使用的版本号为
elastic-job-core 1.1.1
elastic-job-spring 1.1.1
elastic-job-api-core 1.1.1

**Comment by terrymanu** [comment]
版本过于老，我们已不在维护，请升级至2.x

**Comment by ljz0721cx** [comment]
亮哥好：
      嗯嗯，打算升级2.X，
我注册到zk上A,B,C3台机子
1.我操作A机子暂停一段时间
2.A机子恢复暂停后，部分接口不在执行，我看见你是将暂停的节点挂到了zk上，
3.B,C中有一台机子会出现的内存泄漏问题。


想问问亮哥这个可能是什么原因呢？






在 2017-12-28 22:16:36，"张亮" <notifications@github.com> 写道：


版本过于老，我们已不在维护，请升级至2.x

**Comment by ljz0721cx** [comment]
亮哥好：
 升级到2.0.0后使用情况是线程一直在攀升，但是使用率挺低的，是不是正常的情况





在 2017-12-28 22:16:36，"张亮" <notifications@github.com> 写道：


版本过于老，我们已不在维护，请升级至2.x
