### ISSUE TITLE
多网卡存在注册bug 1.1.1版本

### ISSUE THREAD

**Issue by wgou** [dangdangdotcom/elastic-job#202]
今天遇到ElasticJob的一个bug
 出现条件：
   服务器上存在多网卡
现象：
  当服务器重启之后，ElasticJob 本身获取IP的是根据网卡顺序来的，经测试获取网卡顺序是会变的。服务器本身IP为147，VIP 为119.
之前注册ZK的ip为147，重启之后ElasticJob 获取IP为119. 
导致执行的时候147 与119（147） 都会执行，导致数据重复处理。

出现版本：1.1.1 

ElasticJob 获取IP的方法：
 /**
     * 获取本机IP地址.
     * 
     * <p>
     * 有限获取外网IP地址.
     * 也有可能是链接着路由器的最终IP地址.
     * </p>
     * 
     * @return 本机IP地址
     */
    public String getIp() {
        if (null != cachedIpAddress) {
            return cachedIpAddress;
        }
        Enumeration<NetworkInterface> netInterfaces;
        try {
            netInterfaces = NetworkInterface.getNetworkInterfaces();
        } catch (final SocketException ex) {
            throw new JobException(ex);
        }
        String localIpAddress = null;
        while (netInterfaces.hasMoreElements()) {
            NetworkInterface netInterface = netInterfaces.nextElement();
            Enumeration<InetAddress> ipAddresses = netInterface.getInetAddresses();
            while (ipAddresses.hasMoreElements()) {
                InetAddress ipAddress = ipAddresses.nextElement();
                if (isPublicIpAddress(ipAddress)) {
                    String publicIpAddress = ipAddress.getHostAddress();
                    cachedIpAddress = publicIpAddress;
                    return publicIpAddress;
                }
                if (isLocalIpAddress(ipAddress)) {
                    localIpAddress = ipAddress.getHostAddress();
                }
            }
        }
        cachedIpAddress = localIpAddress;
        return localIpAddress;
    }

**Comment by terrymanu** [comment]
请问是否可以通过网卡设置解决此问题

**Comment by wgou** [comment]
可以的，使用排序最后的tun接口来搭载VIP.

**Comment by terrymanu** [comment]
那请问这个issue是可以关闭了么
