### ISSUE TITLE
Console上删除注册管理中心，zookeeper命名空间没有删除

### ISSUE THREAD

**Issue by linbo** [dangdangdotcom/elastic-job#230]
# Env
* OS: Ubuntu 14.04.1 LTS x86_64 
* JDK: openjdk version "1.8.0_111"
* Elastic-job: elastic-job-lite-console-2.0.4-SNAPSHOT.war
* Zookeeper: 3.4.9

# 删除注册中心，zookeeper目录没有删除
1. 在console上新建注册中心，ejob/demo，查看zookeeper，有相应的/ejob/demo创建
2. 删除注册中心，zookeeper上的 /ejob/demo目录仍然存在

# 删除注册中心->zk手动删除目录->重建注册中心，zk没有目录生成
1. 在console上新建注册中心，ejob/demo，查看zookeeper，有相应的/ejob/demo创建
2. 删除注册中心，zookeeper上的 /ejob/demo目录仍然存在
3. 在Zookeeper手动删除 /ejob/demo目录 `rmr /ejob/demo`
4. 在console上新建注册中心，仍然使用 /ejob/demo 目录，注册中心创建成功，zookeeper没有相应目录生成

**Comment by terrymanu** [comment]
我们的考虑是console不影响zk本身。
举个例子，用数据库管理工具，比如mysql workbench，删除了数据库的连接，那个库的schema也并未删除。console不是管理zk的工具，而是管理esjob的工具，对zk的操作不应包含。

**Comment by linbo** [comment]
但是删除后，客户端连接zookeeper的tcp连接还在，这个合理吧
