### ISSUE TITLE
采用Spring命名空间配置时，job-exception-handler配置项不起作用

### ISSUE THREAD

**Issue by xsphere** [dangdangdotcom/elastic-job#232]
<job:simple id="simpleElasticJob" class="cn.jsfund.tsp.job.MyElasticJob"
		registry-center-ref="regCenter" cron="0/10 * * * * ?"
		sharding-total-count="1" sharding-item-parameters="0=A"
		job-exception-handler="cn.jsfund.tsp.job.JsfundJobExceptionHandler" />

目前看job-exception-handler配置不起作用，还是用的默认com.dangdang.ddframe.job.executor.handler.impl.DefaultJobExceptionHandler

**Comment by xsphere** [comment]
经检查是没有在zookeeper上删除该任务后重试，导致新配置没有更新到zookeeper。

**Comment by TaoJieRu** [comment]
添加override = "true"
