### ISSUE TITLE
无法更新zk上sharding-total-count为0的定时任务config节点

### ISSUE THREAD

**Issue by manayi** [dangdangdotcom/elastic-job#237]
使用版本：
            <dependency>
                <groupId>com.dangdang</groupId>
                <artifactId>elastic-job-lite-core</artifactId>
                <version>2.0.3</version>
            </dependency>
问题描述：
       将一个定时任务的sharding-total-count属性配置为0，启动项目正常报错。之后将sharding-total-count修改为正确的大于0的数值（overwrite属性为true），项目仍然报同样的异常，即“sharding-total-count 应该大于0”。
       同时，查看ZK上的config节点数据，发现sharding-total-count仍然为0，没有被覆盖。

**Comment by terrymanu** [comment]
通过api或console修改是无法将sharding-total-count修改为小于1的数值。
直接修改zk导致的问题，应自行清理zk的数据。因此这个issue先不定义为bug了。

**Comment by terrymanu** [comment]
增加了rest api的校验，从java api，rest api以及console三个方面杜绝了sharding-total-count小于1的可能性。
但如果是自行修改zk数据导致的问题，不在这个issue修改的范围之内
