### ISSUE TITLE
ip正则表达式错误

### ISSUE THREAD

**Issue by starryskydog** [dangdangdotcom/elastic-job#238]
SensitiveInfoUtils类中ip正则表达式错误，正确的ipv4正则如下：
 public static final String IPV4_REGEX = "((\\d|[1-9]\\d|1\\d{2}|2[0-4]\\d|25[0-5])(\\.(\\d|[1-9]\\d|1\\d{2}|2[0-4]\\d|25[0-5])){3})";
这个是ipv4的 建议考虑下后期ipv6

**Comment by terrymanu** [comment]
谢谢贡献代码
