### ISSUE TITLE
guava 升级到21.0 遇到的问题

### ISSUE THREAD

**Issue by dragontree101** [dangdangdotcom/elastic-job#257]
guava升级到了21.0版本，启动的时候，执行 
```
CoordinatorRegistryCenter regCenter = new ZookeeperRegistryCenter(zkConfig);
regCenter.init();
````
方法， 找不到 `com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()` 方法

我看了下guava的版本， 在20.0版本的时候 `sameThreadExecutor()` 函数已经被标记为 `@Deprecated` ， 然后guava在21.0版本的时候 已经删除， 希望能够兼容guava的较新的版本， 谢谢。

**Comment by terrymanu** [comment]
guava 21仅支持java8，elastic-job是基于java7的。我们暂时不会考虑java8

**Comment by dragontree101** [comment]
jdk8现在已经很常见，  还是希望能够在后面的版本进行升级
