### ISSUE TITLE
增加作业和ip对应的运行关系

### ISSUE THREAD

**Issue by terrymanu** [dangdangdotcom/elastic-job#26]
如果配置，只有特定的n个IP可以执行某个作业

**Comment by gl2001wl** [comment]
这个功能列入开发计划了吗？
我们需要这个功能，是否能提供较好的实现思路？或许我们能实现。
目前的想法是

1. 每个任务可选一个配置文件，<任务名.properties>在classpath下，注册任务的时候同时将文件中的ip列表注册至zookeeper作为任务白名单使用。
2. 如果多个服务器都有相同任务的话，最后注册的任务会覆盖之前的白名单
3. 通过console可以在线修改白名单
4. leader启动job时，只筛选白名单内可用的server进行分片

**Comment by terrymanu** [comment]
因为esjob整个实现中都未使用prop文件，为了保持一致性，最好还是将信息放入zk。
个人感觉调整zk的目录结构应该就可实现，但是要对原来的数据结构兼容可能还要好好想想

**Comment by gl2001wl** [comment]
fix by https://github.com/dangdangdotcom/elastic-job/pull/89

**Comment by terrymanu** [comment]
duplicate with #117
