### ISSUE TITLE
2.1 版本 安装console ，job状态读取不正确

### ISSUE THREAD

**Issue by WGKLoveStudy** [dangdangdotcom/elastic-job#267]
显示job 状态都为crashed，但实际上 定时任务还在跑……暂定 恢复 按钮也没作用……
希望帮忙看一下，谢了~

**Comment by haocao** [comment]
能否提供相关ZK数据及界面信息？

**Comment by WGKLoveStudy** [comment]
不好意思，图片不知道为什么 一直上传不上来，我配置的最简单的simple，然后 分片写的1，界面上分片项那展示的是null，作业中的作业设置 展示正确，至于zk 您需要什么数据，我看config中 有，但是instances节点下的文件里只有两个服务器命名的ip 空文件

**Comment by WGKLoveStudy** [comment]
config中有作业设置的相关数据……

**Comment by terrymanu** [comment]
请提供zk的dump数据，
参见http://dangdangdotcom.github.io/elastic-job/post/user_guide/lite/features/lite_dump/

**Comment by ZhangChuQiang** [comment]
遇到了同样的问题，2.0.5的console显示状态是PARTIAL_ALIVE，2.1.0显示下线。</br>SimpleJob，    分片配置</br>shardingTotalCount:1</br>shardingItemParameters:0=Beijing,1=Shanghai,2=Guangzhou

**Comment by terrymanu** [comment]
请不要混用不同版本的console，每个console**仅仅**对应其相应版本的elastic-job

**Comment by WGKLoveStudy** [comment]
多谢，问题解决了，统一了console 和 elastic-job的版本。一开始因为git上没更新，打包了2.0.6-snapshot的版本……

**Comment by ZhangChuQiang** [comment]
问题已经解决，谢谢。
