### ISSUE TITLE
精简POM依赖

### ISSUE THREAD

**Issue by jearton** [dangdangdotcom/elastic-job#268]
1.  lombok不应该是compile依赖，应该加上\<scope\>provided\</scope\>  
2. curator-test、junit、unitils-core、mockito-core、h2，这几个依赖是不是应该加上\<scope\>test\</scope\>

这些依赖如果不指定scope，就传递到使用者的项目里了，这是不合理的。我不可能把lombok、junit之类的打包到最终可执行的jar里去的（比如springboot应用）

**Comment by haocao** [comment]
1.lombok应该改为compile依赖。
2.junit、unitils-core、mockito-core、h2已经是test的scope，curator-test应该改为test的scope。
下个版本会更新。
