### ISSUE TITLE
2.1.0 版本控制台，点击按钮后发起两次请求

### ISSUE THREAD

**Issue by gaoyaqiu** [dangdangdotcom/elastic-job#270]
![image](https://cloud.githubusercontent.com/assets/8586794/24861565/c7599ca6-1e2b-11e7-80fe-a4579aca3316.png)

**Comment by haocao** [comment]
![image](https://cloud.githubusercontent.com/assets/687732/24891067/10f829e8-1ea6-11e7-954d-8c6270049551.png)
经测试未发现该情况，待讨论。

**Comment by gaoyaqiu** [comment]
前置条件： 注册中心 大于 1 个
测试步骤： 
          如果注册中心有多个的话，默认登陆后会选择一个注册中心，假设为A。这时候连接注册中心B，然后在回到作业维度的列表中，操作按钮才会出现多次请求的情况。

**Comment by haocao** [comment]
感谢反馈，我们会尽快修复这个问题。
