### ISSUE TITLE
2.1.0 版本，使用AbstractDistributeOnceElasticJobListener监听后，暂停、启用任务异常

### ISSUE THREAD

**Issue by gaoyaqiu** [dangdangdotcom/elastic-job#271]
之前是2.0.5版本，使用这个监听没有问题，升级了2.1.0之后，在使用AbstractDistributeOnceElasticJobListener这个监听后禁用job之后在启用、删除的功能就会出现异常。
调用启用时，会在设定的超时时间之后会继续触发任务，而删除任务的功能无法使用，zk中的节点还存在，没有删掉。

当触发暂停时，每次达到设定的监听超时时间后，控制台就刷出以下的异常信息
测试场景： 单机，起的分片(3片)任务

![image](https://cloud.githubusercontent.com/assets/8586794/24898885/ef0a0aec-1ed0-11e7-9c01-267d3d6273ce.png)

监听中超时时间如果设置很长，那么再次启用之前暂停的任务时就必须等wait结束之后任务才启动起来，并不是调用启用之后就触发notifyAll，不是即时生效的。
![image](https://cloud.githubusercontent.com/assets/8586794/24904324/b90598e6-1ee2-11e7-8f69-2184f9ad7ba5.png)

**Comment by gaoyaqiu** [comment]
[ERROR] 2017-04-11 17:59:30,018 --com.dangdang.ddframe.job.example.job.dataflow.SpringDataflowJob_Worker-1-- [com.dangdang.ddframe.job.executor.handler.impl.DefaultJobExceptionHandler] Job 'com.dangdang.ddframe.job.example.job.dataflow.SpringDataflowJob' exception occur in job processing 
com.dangdang.ddframe.job.exception.JobSystemException: Job timeout. timeout mills is 30000.

**Comment by terrymanu** [comment]
AbstractDistributeOnceElasticJobListener功能感觉没有太多实际意义，而副作用又比较多。我们在考虑删除listener功能，未来考虑采用作业依赖的方式。因此这个bug的修复先暂停。

**Comment by gaoyaqiu** [comment]
谢谢亮哥！

**Comment by terrymanu** [comment]
已确认，这个问题在2.0.5也存在。这是原理决定的，没法修正。只能等待下次重分片之后修正DistributeOnceElasticJobListener的行为。本次发包不会对listener进行提升。只要不是功能衰退，就先不改了，以后会考虑使用功能更加强大的作业依赖完全替换掉listener。
