### ISSUE TITLE
job有时候能运行有时候不能运行

### ISSUE THREAD

**Issue by leohuangjx** [dangdangdotcom/elastic-job#277]
在最新代码2.1版本里,把demo里的例子拿到项目里执行. 有时候5秒正常执行.有时候一直不执行.
监控里显示
状态为 	CRASHED 
分片项 	null
不可用.为什么?
elastic-job-lite 注册中心就一个. 当前运行程序也是一个.

**# 相关环境信息如下**
## 配置文件信息:
`<reg:zookeeper id="regCenter" server-lists="10.168.12.66:2181" namespace="pay-job" base-sleep-time-milliseconds="1000" max-sleep-time-milliseconds="3000" max-retries="3" />
    
<job:simple id="myElasticJob" class="com.uaf.pay.job.MyElasticJob" registry-center-ref="regCenter" sharding-total-count="3" cron="0/5 * * * * ?" sharding-item-parameters="0=Beijing,1=Shanghai,2=Guangzhou" monitor-execution="false" monitor-port="9888" failover="true" description="测试" disabled="false" overwrite="true"  />`

## 主要的job类内容
`@Service
public class MyElasticJob implements SimpleJob {

	@Resource
	private FooRepository fooRepository;

	@Override
	public void execute(ShardingContext shardingContext) {
		System.out.println("-------开始----");
		System.out.println("ShardingItem:" + shardingContext.getShardingItem());
		System.out.println("ShardingParameter:" + shardingContext.getShardingParameter());
		System.out.println("ShardingTotalCount:" + shardingContext.getShardingTotalCount());
		// System.out.println("TaskId:" + shardingContext.getTaskId());
		List<Foo> data = fooRepository.findTodoData(shardingContext.getShardingParameter(), 10);
		for (Foo each : data) {
			fooRepository.setCompleted(each.getId());
		}
		String string = data.toString();
		System.out.println(shardingContext.getShardingParameter() + "长度:" + data.size());
		System.out.println("-------结束----" + string);
		System.out.println();
	}

}`

该类中涉及到的FooRepository 和 Foo 类是在
`elastic-job-master\elastic-job-example\elastic-job-example-jobs`

## 用的的监控 
elastic-job-lite-console-2.0.5.war

**单注册中心,  运行在本地eclipse的tomcat上**.

**Comment by terrymanu** [comment]
请提供能确定的重现条件

**Comment by leohuangjx** [comment]
新增一个job 启动没反应.
` 

    <job:simple id="mySimpleJob" class="com.uaf.pay.job.MySimpleJob" registry-center-ref="regCenter" cron="0/10 * * * * ?" sharding-total-count="3" sharding-item-parameters="0=A,1=B,2=C" description="测试111"/>
`
job内容
`@Service
public class MySimpleJob implements SimpleJob {

	@Override
	public void execute(ShardingContext context) {
		switch (context.getShardingItem()) {
		case 0:
			System.out.println(context.getShardingItem() + context.getShardingParameter());
			break;
		case 1:
			System.out.println(context.getShardingItem() + context.getShardingParameter());
			break;
		case 2:
			System.out.println(context.getShardingItem() + context.getShardingParameter());
			break;
		// case n: ...
		}

	}

}`

**运行一分钟后 没有日志输出.**
**这个时灵时不灵的比较困惑.求解.谢谢.**

**Comment by haocao** [comment]
请先把console更新到2.1.0版本。

**Comment by leohuangjx** [comment]
@haocao 目前就是2.1.0版本. 明天我试一试两台机器一起跑.

**Comment by haocao** [comment]
用的的监控

elastic-job-lite-console-2.0.5.war

单注册中心, 运行在本地eclipse的tomcat上.

这个不是说console用的2.0.5吗？

**Comment by leohuangjx** [comment]
@haocao @terrymanu  已经更新console到2.1.0版本.  确实得到信息比较多. 但显示 分片调整中 ,持续时间比较久,在这个时间段内job没有运行.  
## **当前环境:**
注册中心一个
2个作业
一个tomcat运行中.

2个作业的分片总数都是3.
**是否当前实例只有一个,造成分片一直在调整中.**

**Comment by terrymanu** [comment]
请问问题还是issue一开始提出的那个么？如果不是，请关闭此issue并提出新的issue

**Comment by terrymanu** [comment]
分片调整中请参见实现原理文档。如果确定是bug请提出，问题讨论请在qq群中进行。这里讨论效率较低。谢谢合作

**Comment by leohuangjx** [comment]
## 最新问题跟进情况:
运行一晚上,当只有一个节点在跑两个job 并且这两个job都是分3分片, 一直处于 **分片调整中**  造成job 一晚上一直没跑. 
**如果是两个节点跑, 中间一个节点挂了 会不会也一直在 分片调整中.?**

**Comment by terrymanu** [comment]
我先将这个issue关闭了，有问题请在qq群讨论清楚再提issue，这里讨论效率较低。而且这个issue后续讨论已经不是当时开启issue时的问题了。当时的问题是版本不一致造成的。
