### ISSUE TITLE
2.1.0控制台修改作业校验

### ISSUE THREAD

**Issue by mujourney** [dangdangdotcom/elastic-job#284]
2.1.0控制台修改作业的时候分片总数为1，但是分片序列号/参数对照表却可以修改为0=A，1=B。分片序列号不能大于或等于分片总数，所以这里的1=B明显不符合

**Comment by terrymanu** [comment]
并未做这么细节的校验，顶多是分1片时1=b读不出来而已。如果以后改为两片，之前的配置仍旧可以复用。应该也不算bug。
我们暂时不想在console上花这么大力气，还是想集中在分布式程序核心，因此这个问题先不修改了
