### ISSUE TITLE
英文版的job-console

### ISSUE THREAD

**Issue by microhello** [dangdangdotcom/elastic-job#29]
@terrymanu 
我将elastic-job使用在一个国际化项目中，需要英文版的job-console，希望能够实现，谢谢。

**Comment by terrymanu** [comment]
加上i18n就好，应该不难，我们会在下期集中实现

**Comment by microhello** [comment]
thanks

**Comment by terrymanu** [comment]
目前该任务优先级较低，暂时不会实现。如有需要，希望开源社区人员贡献代码，感谢

**Comment by terrymanu** [comment]
fixed by #359, #360, #361, #362

**Comment by terrymanu** [comment]
为对接dc/os提供英文界面
