### ISSUE TITLE
Lite Console中 关于数据源配置的完善

### ISSUE THREAD

**Issue by wanglong1615** [dangdangdotcom/elastic-job#293]
添加数据源时，增加一个按钮“连接测试”。
点击“连接测试”如果数据源信息正确，则提示连接成功，否则提示连接失败。

**Comment by haocao** [comment]
Fixed in https://github.com/dangdangdotcom/elastic-job/commit/1b3610c541dd33ce4e19d9dda7c3a7a9ff958ea0.
