### ISSUE TITLE
节点间任务可能出现较大延迟

### ISSUE THREAD

**Issue by cjdxhjj** [dangdangdotcom/elastic-job#3]
节点任务由quartz进行调度，但是如果任务节点和主节点或其它节点的时间有大量出入，就会导致较快节点一直阻塞等待主节点分片，较慢节点一直没去执行分片任务。在数据要进行全局一致性保证有的情况下容易造成事务超时或不能实现。建议在节点启动时增加时间同步，比如以主节点数据为基准，如果差距超出某一范围，则进行时间同步

**Comment by cjdxhjj** [comment]
节点任务由quartz进行调度，但是如果任务节点和主节点或其它节点的时间有大量出入，就会导致较快节点一直阻塞等待主节点分片，较慢节点一直没去执行分片任务。在数据要进行全局一致性保证有的情况下容易造成事务超时或不能实现。建议在节点启动时增加时间同步，比如以主节点数据为基准，如果差距超出某一范围，则进行时间同步

**Comment by terrymanu** [comment]
目前作业框架的职责主要定义为作业相关。
时间同步会对整个服务器产生影响，有可能使作业框架产生副作用或带来混淆。
已考虑增加多服务器的时间校对功能，（差值过大报错）但暂时不提供服务器时间修改功能。
