### ISSUE TITLE
统计job数量

### ISSUE THREAD

**Issue by jxctx88** [dangdangdotcom/elastic-job#303]
是否可以默认添加一个名称空间，比如我有simpleJob1,simpleJob2,添加一个默认的名称空间，如：elastic-job,这样zk的目录结构就是：
/elastic-job/simpleJob1
/elastic-job/simpleJob2
这样就比较好统计，同时也容易观察，特别是我们有好多其他框架都是同一个zk的

**Comment by terrymanu** [comment]
这个issue的title和content不符合呀。
如果是统计job数量，console有做，如果是命名空间问题，可以自己随意配置，elastic-job已经将最大的自由度开放出去了，不会自己默认创建一个namespace。

**Comment by jxctx88** [comment]
但是新版的我看不允许有/啊，这样在zookeeper就不能是分节点的啊

**Comment by terrymanu** [comment]
和版本没关系，新版本对zookeeper那里没有做任何改动
