### ISSUE TITLE
Memory leak problem when deployed in Tomcat

### ISSUE THREAD

**Issue by MuchContact** [dangdangdotcom/elastic-job#308]
see examples from https://github.com/MuchContact/elastic-examples

**Comment by guangyun1013** [comment]
我使用jdk7和tomcat-7.0.78没有复现你描述的问题，请问你用的什么版本的，我再试下

**Comment by guangyun1013** [comment]
经过研究发现这跟tomcat的应用销毁机制关系密切，简单来说默认情况下tomcat不会强制销毁webapp创建的线程， 而这些线程的context classloader是webapp classloader，如果webapp停止的时候这些线程没有被正确结束，就 会有指向webapp classloader的引用存在导致webapp classloader无法被回收，进而造成内存泄露。

其他框架例如mysql jdbc驱动，JRE某些classes也存在该问题。我写了一个使用mysql作为数据库的demo验证发现也会存在memory leak问题，所以建议如果将Elastic-Job部署在web容器中运行，直接重启web容器就可以了。

mysql验证demo请参考：https://github.com/guangyun1013/jdbc-demo

**Comment by terrymanu** [comment]
由于长时间无反馈，看起来是tomcat使用的问题的几率比较大， 先关闭了。有需要请再申请
