### ISSUE TITLE
elastic-job-lite-console中作业历史不显示

### ISSUE THREAD

**Issue by IcyLemon** [dangdangdotcom/elastic-job#314]
elastic-job-lite-console 2.1.1版本，作业运行均正常，也增加了监控配置，但作业历史中没有数据。
查看控制台日志，发现报如下错误：
 [com.dangdang.ddframe.job.event.rdb.JobEventRdbSearch] Fetch EventC
ount from DB error:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '[我的数据库名].job_execution_log' doesn't exist
是不是还需要再手工创建表job_execution_log？

**Comment by terrymanu** [comment]
请参照issue模板提供相关信息

**Comment by IcyLemon** [comment]
我是先启动elastic job，再启动的console。

**Comment by IcyLemon** [comment]
通过查看代码找到问题了：我在构造JobScheduler是，用的是如下的构造方法：
JobScheduler(fregCenter, liteJobConfig, elasticJobListeners)；
这个方法中，直接new了一个JobEventBus()，这样就没法使用JobEventRdbConfiguration了。
改用如下的构造方法就好了：
JobScheduler(regCenter, liteJobConfig, jobEventConfig, elasticJobListeners)；

非常感谢，elastic-job-lite是一个很不错的框架，后续会持续关注。
