### ISSUE TITLE
应该支持无侵入的将java bean注册为作业

### ISSUE THREAD

**Issue by IcyLemon** [dangdangdotcom/elastic-job#315]
无论是在1.x版本还是在2.x版本，作业要么必须继承一个基类，要么必须实现一个接口，这对代码有很大的侵入性，使用1.x版本的，升级到2.x，就不能用了，必须修改接口。

由于Quartz中一个任务也需要实现特定接口，因此上述的实现并没有问题，但是既然是更高级的框架，应该可以做到像Spring对Quartz的封装一样，支持将一个普通的Spring管理的java bean的某个方法注册成一个作业，即用户希望如下方式的配置：
<job:simple **bean-ref="xxx.userService"** **method-name="refreshAll"** cron="0/10 * * * * ?" ... />

这里，bean-ref就指向spring管理的某个bean，method-name为bean中的方法，不需要实现任何接口。

其实实现上也不复杂，再做一层包装即可，我们的项目目前就是这么做的，因为需要作为任务的方法事先都开发了，而且量很大，没人愿意再逐一修改接口去实现SimpleJob，差点就不想用这个框架了。因此我们就把每个方法包装为SimpleJob。

因此，希望能考虑增加该功能，特别是用注解就更方便了。

**Comment by terrymanu** [comment]
Elastic job和核心功能是分片，必须提供api用于告知客户端程序如何处理分片。因此接口是必须的。
