### ISSUE TITLE
新版2.1.2的console版本在添加注册中心时命名空间不支持/

### ISSUE THREAD

**Issue by hapic** [dangdangdotcom/elastic-job#321]
版本：2.1.2

新版2.1.2的console版本在添加注册中心时命名空间不支持/
zk在使用时会根据不同的业务组分配不同的根命名空间，使用到zk的地方都会在此命名空间进行新增节点，避免出现节点使用混乱或冲突的情况，但发现2.1.2的console添加注册中心时不在支持使用 / 。

**Comment by noobFly** [comment]
这个不支持指的是前端JS会校验不支持，还是后端校验不支持？ 我这边是JS校验，把它关闭了就好了，后台服务现在看来也没有问题
