### ISSUE TITLE
Lite界面在作业第一次自动触发之前，状态一直为分片调整中

### ISSUE THREAD

**Issue by chulianfeng** [dangdangdotcom/elastic-job#323]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
Lite 2.1.1
### Expected behavior
分片调整在job向zk注册完成后（job第一次自动触发之前）就完成，第一次自动触发前可以手动触发。
### Actual behavior
console中job，在第一次触发之前，状态一直为分片调整中。不能手动触发。

**Comment by haocao** [comment]
Expected behavior
作业在ZK注册完成后，并且未开始调度前会一直处于待分片状态，在leader节点的sharding子节点会有necessary标记。这个时候还没能完成分片，因此不能手动触发调度。
