### ISSUE TITLE
关于StdSchedulerFactory 属性设置问题

### ISSUE THREAD

**Issue by An243201509** [dangdangdotcom/elastic-job#347]
private Properties getBaseQuartzProperties() {
        Properties result = new Properties();
        result.put("org.quartz.threadPool.class", SimpleThreadPool.class.getName());
        result.put("org.quartz.threadPool.threadCount", "1");
        result.put("org.quartz.scheduler.instanceName", this.liteJobConfig.getJobName());
        result.put("org.quartz.jobStore.misfireThreshold", "1");
        result.put("org.quartz.plugin.shutdownhook.class", JobShutdownHookPlugin.class.getName());
        result.put("org.quartz.plugin.shutdownhook.cleanShutdown", Boolean.TRUE.toString());
        return result;
    }

为什么不让 quartz 的属性可配置呢？
org.quartz.jobStore.misfireThreshold 设置那么小， 难道任务超时就必须misfire么？

**Comment by terrymanu** [comment]
值越小越不会执行misfire。elastic job是关掉了quartz本身的misfire，另外提供分布式的misfire功能
