### ISSUE TITLE
2.1.3版本编译生成的elastic-job-lite-console-2.1.3.tar.gz，linux下启动报错

### ISSUE THREAD

**Issue by no7fengye** [dangdangdotcom/elastic-job#354]
Please answer these questions before submitting your issue. Thanks!

2.1.3版本

在bin目录下执行 sh ./start.sh ,报错
./start.sh:行2: $'\r': 未找到命令
./start.sh:行3: 未预期的符号 `$'{\r'' 附近有语法错误
'/start.sh:行3: `show_usage() {

**Comment by terrymanu** [comment]
从windows下载的文件会有windows的换行符。请自行保证shell文件换行符在自己平台的正确性

**Comment by no7fengye** [comment]
多谢亮哥提醒
