### ISSUE TITLE
elasitc-job 多实例和单次定时任务的问题

### ISSUE THREAD

**Issue by xin497668869** [dangdangdotcom/elastic-job#357]
您好, 请教一下, 每一个定时任务都有一个schedule实例一个线程,  请问当时为什么要这样设计呢? 如果定时任务多, 每个服务器上都有n多个线程会不会有问题?  目前业务存在多个只执行一次的定时任务, 执行完不及时清除感觉zookeeper上信息越来越多也是个问题.

**Comment by terrymanu** [comment]
duplicate with #196
