### ISSUE TITLE
基于全局任务调度

### ISSUE THREAD

**Issue by chenguofu1001** [dangdangdotcom/elastic-job#365]
你好，我们的使用场景是有多个任务，每个任务只有一个分片，我试了一下Elastic-Job把所有的任务都分配给第一台主机，其他任务都空闲。即Elastic-Job默认的任务分配算法是基于单个任务的，并没有考虑到多台主机的负载问题。请问有没有办法将这些任务均匀地分配到多台主机？

### Which version of Elastic-Job do you using?
2.1.3

**Comment by terrymanu** [comment]
分片算法可以自己写。请阅读：http://dangdangdotcom.github.io/elastic-job/elastic-job-lite/02-guide/job-sharding-strategy/

**Comment by chenguofu1001** [comment]
其实这应该是一个挺常见的应用场景，官方不考虑增加一个类似的分片策略吗
