### ISSUE TITLE
指定日期手动触发作业

### ISSUE THREAD

**Issue by chenguofu1001** [dangdangdotcom/elastic-job#366]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.3
### Expected behavior
手动触发作业时，可以指定日期，框架将日期信息通知给所有分片运行，请问亮哥在当前版本下该如何实现？

**Comment by terrymanu** [comment]
目前还无法实现，未来的版本会强化手动触发
