### ISSUE TITLE
Spring annotation @Transaction does not work

### ISSUE THREAD

**Issue by gzg55** [dangdangdotcom/elastic-job#372]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
1.0.6
### Expected behavior
The @Transaction should work in a certain job bean.
### Actual behavior
All the Spring AOP seem does not work in a job bean.
### Steps to reproduce the behavior
After i checked the code, i found the SpringJobFactory.newJob exchange all the proxied bean with plain bean. that means all the proxy method(include the @Transaction)will be invalid.
### Please provide the reproduce example codes (such as github link) if possible.
<img width="924" alt="elastic-job_ transaction invalid" src="https://user-images.githubusercontent.com/5988652/27826862-63e9a8a6-60e7-11e7-9279-a5610d598590.png">

**Comment by terrymanu** [comment]
1.0.6版本早已不维护。由于精力有限，我们只维护最新版本。请升级至最新版再试一下，谢谢。

**Comment by gzg55** [comment]
你好，最新版（1.1.1）的这问题已经修复。是从context中取出的proxied bean并直接设入，没有了AopTargetUtils.getTarget()操作。现在正常了。
