### ISSUE TITLE
是否可以用load-success.bs.table替换all.bs.table

### ISSUE THREAD

**Issue by qq592304796** [dangdangdotcom/elastic-job#376]
bootstrapTable的all.bs.table事件会调用doLocale方法加载太多的资源文件,就算一个点击也会触发
![message](https://user-images.githubusercontent.com/26601421/27898419-8b13554a-6258-11e7-91f8-df52f2a1ae8f.png)

**建议的新功能行为**
使用load-success.bs.table替换all.bs.table

**为什么这个新功能是对大多数用户有用的**
减少浏览器客户端的压力

**Comment by terrymanu** [comment]
请降低对console的期望值。我们的关注点在分布式job本身，console只是个简单实现。如有需要请自行加工。
