### ISSUE TITLE
Firefox浏览器点击历史轨迹和历史状态doLocal没有正常执行

### ISSUE THREAD

**Issue by qq592304796** [dangdangdotcom/elastic-job#377]
**问题复现步骤:**
![dolocal](https://user-images.githubusercontent.com/26601421/27898888-920e47b8-625a-11e7-9bcb-bedf23790eb6.png)

**期望的表现:**

可以正常显示中文和英文

IE11/360/Chrome都是正常的.就是FireFox会有这个问题

历史轨迹和历史状态采用的是DOM的配置方式
![dom](https://user-images.githubusercontent.com/26601421/27899001-09a4e87c-625b-11e7-9d78-f87d4b62991d.png)
其他的是作业配置和全局配置好像都是采用js方式去配置的
![js](https://user-images.githubusercontent.com/26601421/27899106-6823538e-625b-11e7-8181-2ab2080bf7fe.png)

不知道是不是这个原因导致的

**Elastic-Job版本:** elastic-job-lite-console 2.1.4
**操作系统及版本:** windows 7 | FireFox 45.0.1

**Comment by terrymanu** [comment]
请降低对console的期望值。我们的关注点在分布式job本身，console只是个简单实现。如有需要请自行加工。
