### ISSUE TITLE
关于时间分配的问题

### ISSUE THREAD

**Issue by zhangjun075** [dangdangdotcom/elastic-job#379]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.4
### Expected behavior
三台服务器，分一片，5秒钟任务执行一次。
### Actual behavior
任务是在一台机器之心，15秒执行一次。
### Steps to reproduce the behavior
step1:
simpleJob1:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1

step2:
run the job

### Please provide the reproduce example codes (such as github link) if possible.

分一片，其他两台也会去空轮训。这个有点不太合理。
建议：
1、要么没台轮流之心。
2、要么在单台执行，但是时间不会被其他两台占用。

**Comment by terrymanu** [comment]
根据描述猜测：
1.可能任务执行一次的时间就是15秒，因此没次才间隔15秒执行。这种情况可视为cron间隔设置不太合理
2.从原理上说，即使分1片也需要三台机器都轮训一次，不然剩下的两条机器怎么知道之分1片，它们不需要执行？而且在分布式场景下，每次执行状况可能都不同，比如：上次执行时服务器a还在，下次就不在了。因此需要每次和注册中心同步信息。

鉴于此，应该可以断定是使用方的问题。如果有合理的优化想法欢迎提出。

**Comment by terrymanu** [comment]
此issue由于长期未有提出人的跟进，因此就此关闭。
