### ISSUE TITLE
Job初始状态可否直接进入正常状态而不是分片待调整状态？

### ISSUE THREAD

**Issue by kzengpeng** [dangdangdotcom/elastic-job#380]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.3

### Expected behavior
希望在Job的初始化状态是正常状态, 希望在Job启动后就可以手动触发任务.

### Actual behavior
Job的初始化状态是 “分片待调整”, 只有当Job的执行时间到达的时候状态才会变更为正常状态. 这样就没办法提前触发任务。

### Steps to reproduce the behavior
重启Job任务的事例, 然后在控制台看到所有的job的初始状态都是 "分片待调整". 无法手动触发任务。

### Please provide the reproduce example codes (such as github link) if possible.
1个事例, 一个分片
    <job:simple id="xxxJob" description="全量数据同步任务" class="com.xxx.XXXJob"
                registry-center-ref="regCenter" cron="0 0 2 * * ? *" sharding-total-count="1" sharding-item-parameters="0=A" />

![github-issue](https://user-images.githubusercontent.com/6295642/28001420-e382626c-655e-11e7-882e-24fbbdbe3975.png)

**Comment by terrymanu** [comment]
目前不可以。这是elasitc-job的原理决定的。它只会在运行前进行分片。这样看目前比较科学，因此暂时不会修改
