### ISSUE TITLE
1.1.1版本Weblogic下报java.lang.IncompatibleClassChangeError错误

### ISSUE THREAD

**Issue by Lyife** [dangdangdotcom/elastic-job#386]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
1.1.1
### Expected behavior
正常编译运行
### Actual behavior
启动报错
### Steps to reproduce the behavior
在使用Weblogic部署Web项目，启动定时器会报java.lang.IncompatibleClassChangeError错误
### Please provide the reproduce example codes (such as github link) if possible.
`import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

import com.chinacreator.appsvr.task.TaskJob1;
import com.chinacreator.appsvr.task.TaskJob2;
import com.dangdang.ddframe.job.api.JobExecutionMultipleShardingContext;
import com.dangdang.ddframe.job.api.JobScheduler;
import com.dangdang.ddframe.job.api.config.JobConfigurationFactory;
import com.dangdang.ddframe.job.api.config.impl.SimpleJobConfiguration;
import com.dangdang.ddframe.job.api.listener.AbstractDistributeOnceElasticJobListener;
import com.dangdang.ddframe.reg.base.CoordinatorRegistryCenter;
import com.dangdang.ddframe.reg.zookeeper.ZookeeperConfiguration;
import com.dangdang.ddframe.reg.zookeeper.ZookeeperRegistryCenter;

public class InitSystemListener implements ServletContextListener{

	private final ZookeeperConfiguration zkConfig = new ZookeeperConfiguration("172.17.81.27:2181", "elasticjob-test123");
	    
	private final CoordinatorRegistryCenter regCenter = new ZookeeperRegistryCenter(zkConfig);
	
	@Override
	public void contextDestroyed(ServletContextEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void contextInitialized(ServletContextEvent arg0) {
        System.out.println("系统启动......");
        regCenter.init();

        final SimpleJobConfiguration simpleJobConfig = JobConfigurationFactory.createSimpleJobConfigurationBuilder("testTaskJob1", 
                TaskJob1.class, 1, "0/10 * * * * ?").build();
        
        final SimpleJobConfiguration simpleJobConfig1 = JobConfigurationFactory.createSimpleJobConfigurationBuilder("testTaskJob2", 
        		TaskJob2.class, 1, "0/30 * * * * ?").build();
      
      
    
        new JobScheduler(regCenter, simpleJobConfig, new SimpleDistributeOnceElasticJobListener()).init();
        new JobScheduler(regCenter, simpleJobConfig1, new SimpleDistributeOnceElasticJobListener()).init();

        System.out.println("定时任务启动......");

		
	}
	
	private class SimpleDistributeOnceElasticJobListener extends AbstractDistributeOnceElasticJobListener {
        
        SimpleDistributeOnceElasticJobListener() {
            super(1000L, 1000L);
        }
        
        @Override
        public void doBeforeJobExecutedAtLastStarted(final JobExecutionMultipleShardingContext shardingContext) {
            System.out.println("------ before simple job start ------");
        }
        
        @Override
        public void doAfterJobExecutedAtLastCompleted(final JobExecutionMultipleShardingContext shardingContext) {
            System.out.println("------ after simple job start ------");
        }
    }

}
`

**Comment by Lyife** [comment]
报错信息如下：

`java.lang.IncompatibleClassChangeError: Found interface com.google.common.base.Equivalence, but class was expected
	at com.google.common.cache.LocalCache$Strength$1.defaultEquivalence(LocalCache.java:389)
	at com.google.common.cache.CacheBuilder.getKeyEquivalence(CacheBuilder.java:299)
	at com.google.common.cache.LocalCache.<init>(LocalCache.java:242)
	at com.google.common.cache.LocalCache$LocalManualCache.<init>(LocalCache.java:4721)
	at com.google.common.cache.CacheBuilder.build(CacheBuilder.java:807)
	at org.apache.curator.framework.imps.NamespaceWatcherMap.<init>(NamespaceWatcherMap.java:33)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:81)
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:145)
	at com.dangdang.ddframe.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:84)
	at com.test.svr.servlet.InitSystemListener.contextInitialized(InitSystemListener.java:32)`

**Comment by terrymanu** [comment]
weblogic 用的guava和elastic-job的guava版本有冲突吧。自己排查下依赖就好了
