### ISSUE TITLE
新建的job配置disabled=true还是可以跑起来

### ISSUE THREAD

**Issue by quintonhsu** [dangdangdotcom/elastic-job#388]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
1.1.1   

### Expected behavior
job不要跑起来

### Actual behavior
job居然跑起来了

### Please provide the reproduce example codes (such as github link) if possible.
这个我新建的一个job, 在预发环境第一次发布应用，disabled的配置已经为true了，但应用发布后这个job还是照常在跑，只能又去控制台上去禁用掉。下面是我的配置：
<bean class="cn.fraudmetrix.billing.job.FeeJob"/>
    <job:simple id="feeJob" class="cn.*.*.job.FeeJob"
                registry-center-ref="regCenter" sharding-total-count="1"
                cron="0 0/2 * * * ?"
                monitor-execution="true" monitor-port="-1" failover="true" overwrite="false"
                disabled="true" description="fee job"/>

**Comment by terrymanu** [comment]
精力有限，因此1.x版本早已废弃，不再维护
