### ISSUE TITLE
com.dangdang.ddframe.job.reg.exception.RegException

### ISSUE THREAD

**Issue by 2345free** [dangdangdotcom/elastic-job#389]
Please answer these questions before submitting your issue. Thanks!

**Comment by 2345free** [comment]
Elastic-Job 2.1.5
异常:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'regCenter': Invocation of init method failed; nested exception is com.dangdang.ddframe.job.reg.exception.RegException: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout

**Comment by terrymanu** [comment]
与zk连接超时。这样的issue没有意义，请谨慎判断并提出真正有意义的issue，谢谢合作

**Comment by trying-cui** [comment]
这类异常我也遇到过。不过，经过我多次测试，发现正如 @terrymanu 所说，是与zk连接超时。而我这边连接超时，是因为zk服务器设置了防火墙，当我使用vpn之后，就没问题了。仅供参考！
