### ISSUE TITLE
手动触发作业，作业如果配置了misfire 为true 。这次操作会导致作业执行两遍

### ISSUE THREAD

**Issue by Ah39** [dangdangdotcom/elastic-job#390]
quartz 执行作业的时候会判断是否misfire，因为手动触发，不是cron的时间，quartz判定为misfire，会回调 triggerMisfired接口。
正常触发一次，misfire 执行一次，共两次

**Comment by terrymanu** [comment]
这个问题应该在很早之前的版本解决了。请升级至最新版本试一下
