### ISSUE TITLE
Can elastic-job create schedule jobs with deferent intervals?

### ISSUE THREAD

**Issue by xuuz** [dangdangdotcom/elastic-job#397]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
Newest

### Expected behavior

Can create jobs each jobs has each own interval schedule

### Actual behavior

Can create jobs with same interval cron j

**Comment by terrymanu** [comment]
for design reason, we prefer every job has their own  interval schedule.
That is easy to control only one job instance is running when concurrent job instances if trigger overlapped.
