### ISSUE TITLE
同一个class 注册多任务问题

### ISSUE THREAD

**Issue by wgou** [dangdangdotcom/elastic-job#398]
数据同步会消耗较高的内存. 故想任务拆分为多个时段执行。
但elasticjob 不支持这类方式，请问除了每个任务写一个独立的 class之外，有没有别的解决方式。
因同步模块代码一致，copy成另外一个class 感觉不怎么好。

    <job:simple
            id="recipetHeaderJob"
            class="com.retail.vrm.biz.bean.task.RecipetHeaderTask"
            registry-center-ref="retailVrmCenter"
            cron="${job.recipet.cron}"
            sharding-total-count="2"
            sharding-item-parameters="0=300,1=300"
            monitor-execution="true"
            failover="true"
            overwrite="true"/>

    
    <job:simple
            id="recipetHdHeaderJob"
            class="com.retail.vrm.biz.bean.task.RecipetHeaderTask"
            registry-center-ref="retailVrmCenter"
            cron="${job.recipethd.cron}"
            sharding-total-count="2"
            sharding-item-parameters="0=305,1=305"
            monitor-execution="true"
            failover="true"
            overwrite="true"/>
            
     
    <job:simple
            id="recipetXbHeaderJob"
            class="com.retail.vrm.biz.bean.task.RecipetHeaderTask"
            registry-center-ref="retailVrmCenter"
            cron="${job.recipethd.cron}"
            sharding-total-count="2"
            sharding-item-parameters="0=307,1=307"
            monitor-execution="true"
            failover="true"
            overwrite="true"/>

**Comment by terrymanu** [comment]
dup with #64
请升级
