### ISSUE TITLE
elastic-job是否支持任务加锁

### ISSUE THREAD

**Issue by jordandandan** [dangdangdotcom/elastic-job#399]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Expected behavior
任务执行时间可能比cron周期循环执行的间隔要长，如果发现上一次任务未执行完，本次任务则不执行，目前项目是基于redis加锁实现，elastic-job是否支持类似的配置，不使用外部加锁，通过配置任务某个属性能够达到这种效果

**Comment by terrymanu** [comment]
此类问题属于业务范畴，应在作业中控制较好
