### ISSUE TITLE
[未确定的问题] 任务不能保证全局成功

### ISSUE THREAD

**Issue by cjdxhjj** [dangdangdotcom/elastic-job#4]
节点只能统计或保证执行分片的事务性，没办法在全局上做一个控制，可能出现部分数据操作失败，建议在每个分片执行前和全部分片完成时检查zk中是否有失败节点，如果有，就回调任务中roolback接口将节点前面做过的分片任务进行回滚。建议在任务上加上roolback相关回调

**Comment by terrymanu** [comment]
技术上可行，但使用perpetual类型Job，理想的做法是作业一直不停止，不停的返回数据。
加上全体数据的rollback是否具有通用性，毕竟大多数情况下rollback全部作业处理的数据，性能瓶颈会比较大
另一个问题就是需要开启executionMonitor才能判断是否全部作业都已经运行完毕，也就是说，全局回调会受配置的影响，会大幅增加使用的复杂度

欢迎讨论，目前的想法是使用OneOff类型的job可以自由化定制，但有好的想法请留言

**Comment by gl2001wl** [comment]
感觉加入分布式事务的feature在调度平台里不适合

**Comment by terrymanu** [comment]
增加前置和后置任务功能，与#2合并
