### ISSUE TITLE
How to manage the dependencies between jobs?

### ISSUE THREAD

**Issue by pink-lucifer** [dangdangdotcom/elastic-job#405]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Expected behavior
N/A
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Please provide the reproduce example codes (such as github link) if possible.
N/A

For a typical nightly/intraday batch, there is gonna be multiple dependent, independent jobs,  is there a existing method to manage the dependencies of jobs - especially one have to run after another while utilizing elastic job?

Fyi ... no  luck finding one via  http://elasticjob.io/docs/elastic-job-lite/02-guide/config-manual/

**Comment by terrymanu** [comment]
cannot support this feature now

**Comment by pink-lucifer** [comment]
Understood, thx a lot,

One more question: is there an expected GA schedule for Workflow, DAG items on RoadMap?
