### ISSUE TITLE
我已经配置了事件监听，DB的表中job_execution_log已经有数据了，但是在控制台查不出数据

### ISSUE THREAD

**Issue by chaletli** [dangdangdotcom/elastic-job#406]
已经通过
JobEventConfiguration jobEventConfig = new JobEventRdbConfiguration(dataSource);
配置了监听，DB中也有每次执行的监控数据，但是在控制台的Job trace界面，怎么查不到数据

**Comment by terrymanu** [comment]
https://www.oschina.net/question/2267663_2266049
请知晓，我们不会再将精力投入在这里。
