### ISSUE TITLE
add nature language description for crontab  expression

### ISSUE THREAD

**Issue by lovepoem** [dangdangdotcom/elastic-job#411]
I use version 2.1.4
 
I want to add nature language description for crontab expression

**Comment by terrymanu** [comment]
我们不会在对界面进行任何维护，我们的关注点在分布式调度本身，Console仅仅是提供给用户的demo，如有需要，请随意修改。请知悉。

**Comment by lovepoem** [comment]
JobOne | 1 | 0 0 0 * * ? | 在上午12:00 |   | OK | Update Detail Trigger Disable Shutdown
-- | -- | -- | -- | -- | -- | --
JobTwo | 1 | 0 0 0 * * ? | 在上午12:0


The example is above
