### ISSUE TITLE
guava能不能不要依赖，其中用到的方法自己实现就好了。

### ISSUE THREAD

**Issue by centifocus** [dangdangdotcom/elastic-job#412]
elastic-job依赖guava是18，而项目中还会加入其他依赖guava的jar，会冲突。同时项目想用guava 23版本，也因此冲突。

**Comment by terrymanu** [comment]
我们也只能快速实现，无法做到所有东西都不依赖。如果需要，可自行实现，欢迎提供pr

**Comment by ddatsh** [comment]
可以用shade插件，打包完后，包名自动改掉，不影响业务代码 用自己的guava
