### ISSUE TITLE
建议把ShardingService类中私有方法waitingOtherJobCompleted重命名为waitingOtherShardingItemCompleted

### ISSUE THREAD

**Issue by newajax-1** [dangdangdotcom/elastic-job#414]
作业分片服务ShardingService类中有个私有方法：waitingOtherJobCompleted命名不是很合理。
该方法的作用是等待其他分片完成。所以建议命名为waitingOtherShardingItemCompleted可能会更好。

**Comment by terrymanu** [comment]
已合并pr
