### ISSUE TITLE
elastic-job-cloud-scheduler下配置文件中换行符是windows风格，linux下使用报错

### ISSUE THREAD

**Issue by renbaoyu** [dangdangdotcom/elastic-job#416]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Please provide the reproduce example codes (such as github link) if possible.
elastic-job-cloud-scheduler下bin/dcos.sh,bin/start.sh,conf/elastic-job-cloud-scheduler.properties,conf/auth.properties换行符是windows风格的，在linux下使用报错

**Comment by renbaoyu** [comment]
elastic-job-cloud-scheduler下bin/dcos.sh,bin/start.sh,conf/elastic-job-cloud-scheduler.properties,conf/auth.properties换行符是windows风格的，在linux下使用报错

**Comment by terrymanu** [comment]
应该是你自己在windows下载后copy到linux所致。我们开发均使用mac系统，不会产生win换行符，请知悉。
