### ISSUE TITLE
elastic-job-common-core依赖里不应该出现log4j

### ISSUE THREAD

**Issue by jearton** [dangdangdotcom/elastic-job#419]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using? 
2.0.5+

### Expected behavior
去掉log4j依赖，或者变成test scope

### Actual behavior
任何通用框架都不应该强依赖具体的日志实现，而且log4j用的人很少了，大多数都用logback或log4j2

**Comment by terrymanu** [comment]
请问您是否需要再认真核实一下？我们应该从未使用过log4j，请核实下pom.xml

**Comment by jearton** [comment]
<img width="1359" alt="default" src="https://user-images.githubusercontent.com/10370433/30991720-c5ef23e8-a4d8-11e7-8ce1-c4aa48f66ece.png">

**Comment by jearton** [comment]
请看截图，事实说话

**Comment by terrymanu** [comment]
dup with #421
