### ISSUE TITLE
AbstractElasticJob stop什么场合设置成false

### ISSUE THREAD

**Issue by jiang2015** [dangdangdotcom/elastic-job#42]
代码中没有找到设置成false 的场合， 停止作业的方法JobScheduler stopJob 方法中设置成 true。
是不是在resumeCrashedJob 恢复成false呢？

**Comment by terrymanu** [comment]
设置为false是通过web console。core中没有。web console和core无直接交互，都是通过zk。所以只要在zk上加上stoped标记，作业就会停止。web console的停止按钮和恢复按钮就是直接操作zk的数据
