### ISSUE TITLE
建议对elastic-job-common-core项目的guava、gson依赖进行升级

### ISSUE THREAD

**Issue by jearton** [dangdangdotcom/elastic-job#420]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.0.5+

### Expected behavior
建议对guava、gson的版本进行升级，目前用的版本很旧了

**Comment by terrymanu** [comment]
我们不会对guava等进行升级。理由：目前的guava是支持jdk 1.7的最后一个版本。请知晓。另外gson的升级也不在我们的考虑范畴之内，我们追求的是稳定而不是版本的迭代，有需要自己处理依赖即可
