### ISSUE TITLE
elastic-job-lite-core带入了log4j依赖，请看截图

### ISSUE THREAD

**Issue by jearton** [dangdangdotcom/elastic-job#421]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5

### Expected behavior
去掉log4j依赖

### Actual behavior
<img width="1359" alt="default" src="https://user-images.githubusercontent.com/10370433/30991807-42cf5dce-a4d9-11e7-8e60-c6b672ef53b2.png">

**Comment by terrymanu** [comment]
应该是zookeeper或curator带的，和elastic job无关。自行exclude即可
