### ISSUE TITLE
spring boot 多个Dataflow job只执行一个，

### ISSUE THREAD

**Issue by zsw12013** [dangdangdotcom/elastic-job#423]
spring boot  job 2.1.5版本
spring boot job 多个Dataflow job只执行一个，执行最后一个，
官方的列子 我试着加了一个Dataflow job，出现了同样的问题，
在线急。公司的计划用的是这个，影响很大，希望有人赶紧出来看一下，，，
在线等 雪地里跪求等
`
TestDataTestDataTestData======0
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:37:35 | Thread: 60 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:37:35 | Thread: 62 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:37:35 | Thread: 64 | SIMPLE
TestDataTestDataTestData======1
TestDataTestDataTestData======2
TestDataTestDataTestData======0
TestDataTestDataTestData======1
TestDataTestDataTestData======2
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 0 | Time: 23:37:40 | Thread: 80 | SIMPLE
Item: 2 | Time: 23:37:40 | Thread: 82 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:37:40 | Thread: 81 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:37:45 | Thread: 83 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:37:45 | Thread: 64 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:37:45 | Thread: 84 | SIMPLE
TestDataTestDataTestData======2
TestDataTestDataTestData======1
TestDataTestDataTestData======0
TestDataTestDataTestData======0
TestDataTestDataTestData======1
TestDataTestDataTestData======2
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:37:50 | Thread: 60 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:37:50 | Thread: 60 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:37:50 | Thread: 62 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:37:55 | Thread: 82 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:37:55 | Thread: 81 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:37:55 | Thread: 83 | SIMPLE
TestDataTestDataTestData======0
TestDataTestDataTestData======1
TestDataTestDataTestData======2
TestDataTestDataTestData======0
TestDataTestDataTestData======1
TestDataTestDataTestData======2
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:38:00 | Thread: 64 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:38:00 | Thread: 64 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:38:00 | Thread: 64 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======0
Item: 0 | Time: 23:38:05 | Thread: 80 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======1
Item: 1 | Time: 23:38:05 | Thread: 80 | SIMPLE
SpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJobSpringSimpleJob======2
Item: 2 | Time: 23:38:05 | Thread: 80 | SIMPLE
TestDataTestDataTestData======0
TestDataTestDataTestData======1
TestDataTestDataTestData======2`

SpringDataflowJob  官方的列子 我加了日志了，
最后没有打印出  只有TestData  的日志

**Comment by terrymanu** [comment]
你打印出来的日志不是3个分片都执行了么？

**Comment by zsw12013** [comment]
@terrymanu 不是这个意思，我的意思我写了两个定时任务，两个都是实现Dataflow 的job，
只执行第二个，第一个不执行
第一个配置
![qqqqqq](https://user-images.githubusercontent.com/4253279/31313148-d28622c0-ac0b-11e7-95ff-7cea1a800c12.png)
`
@Configuration
public class AutoCheckJobConfig {
    @Resource
    private ZookeeperRegistryCenter regCenter;
    @Resource
    private JobEventConfiguration jobEventConfiguration;
    @Bean
    public DataflowJob dataflowJob() {
        return new AutoCheckJob();
    }

    @Bean(initMethod = "init")
    public JobScheduler dataflowJobScheduler(final DataflowJob dataflowJob, @Value("${autoCheckJob.cron}") final String cron, @Value("${autoCheckJob.shardingTotalCount}") final int shardingTotalCount,
                                             @Value("${autoCheckJob.shardingItemParameters}") final String shardingItemParameters,@Value("${autoCheckJob.jobParameter}") final String jobParameter) {
        return new SpringJobScheduler(dataflowJob, regCenter, getLiteJobConfiguration(dataflowJob.getClass(), cron, shardingTotalCount, shardingItemParameters,jobParameter), jobEventConfiguration);
    }

    private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends DataflowJob> jobClass, final String cron, final int shardingTotalCount, final String shardingItemParameters,final String jobParameter) {

        return LiteJobConfiguration.newBuilder(new DataflowJobConfiguration(JobCoreConfiguration.newBuilder(
                jobClass.getName(), cron, shardingTotalCount).shardingItemParameters(shardingItemParameters).jobParameter(jobParameter).build(), jobClass.getCanonicalName(), false)).overwrite(true).build();
    }
}
`
第二个配置


![22222222222](https://user-images.githubusercontent.com/4253279/31313160-559294b4-ac0c-11e7-87f8-77cd9d596f3f.png)
`
@Configuration
public class QueryTradingResultJobConfig {

    @Resource
    private ZookeeperRegistryCenter regCenter;
    @Resource
    private JobEventConfiguration jobEventConfiguration;
    @Bean
    public DataflowJob dataflowJob() {
            return new QueryTradingResultJob();
    }

    @Bean(initMethod = "init")
    public JobScheduler dataflowJobScheduler(final DataflowJob dataflowJob, @Value("${queryTradingResultJob.cron}") final String cron, @Value("${queryTradingResultJob.shardingTotalCount}") final int shardingTotalCount,
                                             @Value("${queryTradingResultJob.shardingItemParameters}") final String shardingItemParameters, @Value("${queryTradingResultJob.jobParameter}") final String jobParameter) {
        return new SpringJobScheduler(dataflowJob, regCenter, getLiteJobConfiguration(dataflowJob.getClass(), cron, shardingTotalCount, shardingItemParameters,jobParameter), jobEventConfiguration);
    }

    private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends DataflowJob> jobClass, final String cron, final int shardingTotalCount, final String shardingItemParameters, final String jobParameter) {

        return LiteJobConfiguration.newBuilder(new DataflowJobConfiguration(JobCoreConfiguration.newBuilder(
                jobClass.getName(), cron, shardingTotalCount).shardingItemParameters(shardingItemParameters).jobParameter(jobParameter).build(), jobClass.getCanonicalName(), false)).overwrite(true).build();
    }
}
`
然后只执行QueryTradingResultJob 这个job 第一个不执行

**Comment by zsw12013** [comment]
现在我吧
`@Bean
     public DataflowJob  `
和
`@Bean(initMethod = "init")
    public JobScheduler `
的名字改了，
现在只执行第一个任务，第二个不执行


![bbb](https://user-images.githubusercontent.com/4253279/31313433-b775c4c2-ac15-11e7-91b5-cbac5dca9088.png)
![a](https://user-images.githubusercontent.com/4253279/31313435-c05efe64-ac15-11e7-8f5a-66b62f09e3de.png)

**Comment by terrymanu** [comment]
dump一下把内容贴出来

**Comment by zsw12013** [comment]
稍等 项目是能启动完成 就是感觉有一个job没有启动起来，看控制台只有一个job，应该是有两个才对
![job](https://user-images.githubusercontent.com/4253279/31314114-c8f31bb8-ac2a-11e7-9f55-b4ba0bcf101e.png)
稍等我贴一下dump

**Comment by zsw12013** [comment]
问题已找到了
定义JobConfig的时候注意 3个地方
1
 ` @Bean
     public DataflowJob queryTradingResultJob() {
            return new QueryTradingResultJob();
    }`
 
2 
` @Bean(initMethod = "init")
    public JobScheduler queryTradingResultDataJobScheduler(`

以上两个地方方法名不能一样，不然会覆盖上一个任务，导致最终只执行最后一个

3  、
` private LiteJobConfiguration getLiteJobConfiguration(final Class<? extends QueryTradingResultJob> jobClass,`
继承自己的定义job

**Comment by terrymanu** [comment]
真心不建议你提这样的issue，这种issue别人帮不了你什么

**Comment by zsw12013** [comment]
删除吧我这边删除不了，

**Comment by zsw12013** [comment]
嗯好，确实不该 删除吧 我这边删除不了
