### ISSUE TITLE
官网上介绍的 常驻任务 具体含义和设置方法

### ISSUE THREAD

**Issue by dongyado** [dangdangdotcom/elastic-job#425]
查了最新的文档，没有发现常驻任务的设置方法。

我理解的 常驻任务 是一启动就一直在运行，任务不会结束，除非停掉ejob的主进程。

任务的配置参数没有发现配置 常驻任务的参数，只有 cron 来配置定时启动。

如理解有误，还请指出

**Comment by terrymanu** [comment]
http://elasticjob.io/docs/elastic-job-cloud/02-guide/cloud-restful-api/
搜一下“常驻作业”这个关键字

**Comment by mccxj** [comment]
> http://elasticjob.io/docs/elastic-job-cloud/02-guide/cloud-restful-api/
> 搜一下“常驻作业”这个关键字

说实话，上面没有具体说明这个常驻作业是个什么概念

**Comment by Leonidasz** [comment]
@mccxj 
常驻作业:初始化时间长,触发间隔短,实时性要求高,资源配备充足。
瞬时作业:初始化时间短,触发间隔长,可延迟,资源错峰处理。
这涉及的是elastic-job-cloud相关的问题，不建议在此展开。
