### ISSUE TITLE
增加job监控及报警接口

### ISSUE THREAD

**Issue by a2833986889** [dangdangdotcom/elastic-job#44]
友好定义出 报警接口 ，。 至于怎么报警抽象接口又各个业务自己实现。！  把如何监控详细定义出来

**Comment by terrymanu** [comment]
目前的监控是基于zk，http://dangdangdotcom.github.io/elastic-job/post/execution_monitor/
请详细讨论下，目前还有哪些东西需要监控，用什么方式监控

**Comment by gl2001wl** [comment]
如果要知道trigger的历史信息怎么实现好？通过zk还是让每个quartz使用jdbc store？
目前都是本次上上次执行状态，对于异常不挂起的job历史失败不好排查。
另外对于异常挂起的job，没有在zk中更新状态至failed，还是completed，这也是个问题。

**Comment by terrymanu** [comment]
是的，如果需要查询历史，需要看日志，或者设计一种统一的策略把错误信息发布出去。目前看，基于elk的日志分析居多吧

**Comment by gl2001wl** [comment]
实时监控报警可以考虑使用JMX的MXBean的Notification来做？普通的写日志然后外部统一日志平台拉取比较合适。

**Comment by terrymanu** [comment]
目前监控功能已通过event log的方式实现。报警功能不在elastic-job范畴之内
