### ISSUE TITLE
设置unscheduleAllTriggers=true后挂起任务在监控里没有体现

### ISSUE THREAD

**Issue by gl2001wl** [dangdangdotcom/elastic-job#45]
@Override
    public void handleJobExecutionException(JobExecutionException jobExecutionException) throws JobExecutionException {
        jobExecutionException.setUnscheduleAllTriggers(true);
        throw jobExecutionException;
    }
当拦截异常后，trigger已经挂起，但监控里没有体现这种状态。

期望结果：
    当设置unscheduleAllTriggers=true后，如果trigger被挂起，能同时在console中显示状态为exception

**Comment by terrymanu** [comment]
请问这是哪个类里的代码

**Comment by gl2001wl** [comment]
这是我job实现类里自己写的代码，根据quartz的规则，在handleJobExecutionException中
jobExecutionException.setUnscheduleAllTriggers(true);
当调用这个语句后，之后的trigger都会挂起了，任务不会再执行。但是目前的监控，或者说任务状态没有处理这块

**Comment by terrymanu** [comment]
新2.0版本已决定完全对外屏蔽quartz的api
