### ISSUE TITLE
使用类似disruptor的ringBuffer的生产/消费者模式来处理dataFlow提升效率

### ISSUE THREAD

**Issue by gl2001wl** [dangdangdotcom/elastic-job#47]
目前dataFlow的处理是阻塞队列模式
loadData->
             ->DataExecutionThread1
             ->DataExecutionThread2
             ->DataExecutionThread3
             ->...
waiting for execution complete
...
next round loadData->
             ->DataExecutionThread1
             ->DataExecutionThread2
             ->DataExecutionThread3
             ->...

这种阻塞读的模式在快速批量数据处理中性能不够好，应该可选为生产/消费模式

**Comment by terrymanu** [comment]
可以讨论下。esjob是定时任务框架，本应定时触发，先取再处理，用生产/消费者模式的好处在于一个一直在运行中的进程。
对于只在某个时段运行的作业，是否更适合顺序处理

**Comment by gl2001wl** [comment]
对于Throughput job，本意应该是在一次任务中连续不断的批量处理数据？或许用BlockingQueue会更高效，避免读和处理线程的相互阻塞

**Comment by terrymanu** [comment]
dataflow类型已在2.x中进行修改，Throughput类型已删除。
