### ISSUE TITLE
【一般性问题】job运行在多个机器，引发的时间同步问题。

### ISSUE THREAD

**Issue by amao12580** [dangdangdotcom/elastic-job#6]
多机运行job时，job在各自所在机器上，由quartz组件单机调度。
quartz组件是强时间依赖的组件，时间依赖于本机的操作系统时间。
如果机器之间的操作系统时间出现不一致，而job的运行与时间存在逻辑关系，则会引发job运行混乱。

建议：每台机器启动运行实例时，如果有job配置为强时间依赖，则与zookeeper进行时间校对，如果差异过大，抛出启动异常，中断启动。

其实只要主机间安装ntp组件，保持运行，并实时链入时间同步服务器，也可以解决这个问题。

强时间依赖的job示例：
某job，名为A，A的每次运行，需要检查最后一次运行的时间与当前时间的差值，是否低于30秒，如果低于则退出运行，反之则继续运行。
如果A部署在2台机器上，这两台机器的操作系统时间存在差异，差值为20分钟。则A在分布式运行在2台机器时，会出现问题。

**Comment by terrymanu** [comment]
fixed
