### ISSUE TITLE
[Bug] 分片和主节点选举同时发生时，死锁问题解决

### ISSUE THREAD

**Issue by terrymanu** [dangdangdotcom/elastic-job#61]
分片和主节点选举同时发生时，可能发生死锁。

1. 通过修正分片中条件判断改善多线程环境下分片锁死的可能性。
2. 将分配分片步骤和清理分片标记步骤放入同一事务，保持数据完整性，并防止分片成功后分片标记未清理导致的死锁可能性。
3. 将清理分片步骤放入同一事务，保持数据完整性。

**Comment by terrymanu** [comment]
fixed at 1.0.5

**Comment by Ah39** [comment]
https://github.com/elasticjob/elastic-job-lite/commit/7db63922bdc22a7e198506b8754ab0a5dbcc1893
