### ISSUE TITLE
Spring命名空间，若注册多个同Class的作业Bean，会导致作业Bean查找不准确

### ISSUE THREAD

**Issue by terrymanu** [dangdangdotcom/elastic-job#64]
目前作业的spring命名空间是使用作业类型查找bean，如果注册两个或以上的相同类型的bean，会导致查找不准确，多个bean会全部对应至第一个bean。

**Comment by tooxin** [comment]
我加日志看主要是SpringJobFactory的newjob非线程安全吧，spring的bean默认单例， 加同步锁是否能解决？

**Comment by deific** [comment]
使用spring可以改成bean为property模式，即同一任务class可以配置多个任务实例去运行。另外建议增加用户自定义的扩展参数，因为同一任务class的多个任务实例的情况可能只是各自任务参数不一样，而这种参数可能是多样的，比如数据库连接配置参数，可以通过用户自定义扩展参数传进任务。用户自定义扩展参数觉得可以使用bean的方式配置，具体传什么由用户自己实现。

**Comment by huisongyang** [comment]
这个bug有点矛盾，使用spring的@Component注解job类就会出现这个问题，觉得这个SpringJobFactory类有点多余
`for (Job each : applicationContext.getBeansOfType(Job.class).values()) {
                if (AopUtils.getTargetClass(each) == bundle.getJobDetail().getJobClass()) {
                    job = each;
                    break;
                }
            }`

**Comment by panshiming** [comment]
如何Job class类只想单例的话，通过jobParameter区别不同任务，这个问题有什么解决方法么？

**Comment by terrymanu** [comment]
以后再使用spring命名空间无需再在ElasticJobBean上再定义@Compoment或在spring xml声明
