### ISSUE TITLE
是否支持业务中开放交给用户动态创建定时任务？

### ISSUE THREAD

**Issue by kazaff** [dangdangdotcom/elastic-job#66]
> 因为作业都是在首次运行时自动添加，使用运维平台添加作业并无必要。

新手，刚细读了一遍文档
感觉文档中的上面那句话写的很武断，从代码例子上看应该是允许业务中手动增删改任务的，监控系统的文档中为何说“并无必要”？

**Comment by terrymanu** [comment]
目前无实现思路，如有想法可提供。
以当前的框架难于实现通过控制台添加作业的功能
而且作用通过程序启动自动添加，请问什么场景需要手动从控制台添加

**Comment by fzsens** [comment]
@kazaff 想要的应该是现在工程中创建Job，然后在Elastic-Job 控制台中启动这个Job；如果我的理解是对的话，应该可以在Elastic-job框架中设置监听，来完成这部分Job的启动。

**Comment by liujiesmart** [comment]
可以参考下 azkaban  linkendin 的开源

**Comment by gaoyaqiu** [comment]
自己扩展 new JobScheduler().init(); 就行了，可以实现动态创建Job

**Comment by txm119161336** [comment]
应用场景就是当前的job可以在运行时关闭，并且重新启动，这个功能目前貌似尚未提供

**Comment by ZhangShufan15** [comment]
@txm119161336   看源码是实现了全部任务的暂停和启动的，可以在console中使用。[见这里](https://github.com/dangdangdotcom/elastic-job/blob/master/elastic-job-core/src/main/java/com/dangdang/ddframe/job/internal/schedule/JobScheduleController.java)

**Comment by terrymanu** [comment]
添加作业是作业分发功能，elastic-job-lite无法提供。已确定在elastic-job-cloud中提供
