### ISSUE TITLE
[CannotReproduce]作业经常出现断篇的情况，执行后面就不再执行了

### ISSUE THREAD

**Issue by zhangzhenhuajack** [dangdangdotcom/elastic-job#68]
![abc](https://cloud.githubusercontent.com/assets/11462004/13838134/804bf672-ec4c-11e5-9d48-974a183ef9ec.png)

代码如下：
`
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.dangdang.ddframe.job.api.JobExecutionMultipleShardingContext;
import com.dangdang.ddframe.job.plugin.job.type.simple.AbstractSimpleElasticJob;
import com.yuntu.master.job.systems.service.MasterUserCustomerVisitLinkSumService;
import com.yuntu.master.job.util.Page;

/**
 * Created by jack on 2/1/16.
 */
@Component
public class MasterUserCustomerVisitLinkSumJob extends AbstractSimpleElasticJob {
	@Autowired
	MasterUserCustomerVisitLinkSumService masterUserCustomerVisitLinkSumService;
	/**
	 * 执行作业.浏览30天的数据计算
	 *
	 * @param shardingContext 作业分片规则配置上下文
	 */
	@Override
	public void process(JobExecutionMultipleShardingContext shardingContext) {
		// 自动发起提现申请
		execute();
	}

	public void execute() {
		System.out.println("#######figureUpCustomerVisitSum####begin");
		masterUserCustomerVisitLinkSumService.figureUpVisitSum(new Page());
		System.out.println("#######figureUpCustomerVisitSum####over");

	}
}`
xml配置如下：

> 

> `<bean class="com.dangdang.ddframe.job.spring.schedule.SpringJobScheduler"
		  init-method="init">
		<constructor-arg ref="regCenter" />
		<constructor-arg>
			<bean class="com.dangdang.ddframe.job.api.JobConfiguration">
				<constructor-arg name="jobName" value="MasterUserCustomerVisitLinkSumJob-Master" />
				<constructor-arg name="jobClass" value="com.yuntu.master.job.systems.MasterUserCustomerVisitLinkSumJob" />
				<constructor-arg name="shardingTotalCount" value="1" />
				<constructor-arg name="cron" value="0 */10 * * * ?" />
				<property name="overwrite" value="${job.overwrite}"/>
				<property name="description" value="计算潜客的的浏览次数和最后查看时间"/>
			</bean>
		</constructor-arg>
	</bean>`

**Comment by zhangzhenhuajack** [comment]
<bean class="com.dangdang.ddframe.job.spring.schedule.SpringJobScheduler"
		  init-method="init">
		<constructor-arg ref="regCenter" />
		<constructor-arg>
			<bean class="com.dangdang.ddframe.job.api.JobConfiguration">
				<constructor-arg name="jobName" value="MasterUserCustomerVisitLinkSumJob-Master" />
				<constructor-arg name="jobClass" value="com.yuntu.master.job.systems.MasterUserCustomerVisitLinkSumJob" />
				<constructor-arg name="shardingTotalCount" value="1" />
				<constructor-arg name="cron" value="0 */10 * * * ?" />
				<property name="overwrite" value="${job.overwrite}"/>
				<property name="description" value="计算潜客的的浏览次数和最后查看时间"/>
			</bean>
		</constructor-arg>
	</bean>

**Comment by zhangzhenhuajack** [comment]
> 
<bean class="com.dangdang.ddframe.job.spring.schedule.SpringJobScheduler"
		  init-method="init">
		<constructor-arg ref="regCenter" />
		<constructor-arg>
			<bean class="com.dangdang.ddframe.job.api.JobConfiguration">
				<constructor-arg name="jobName" value="MasterUserCustomerVisitLinkSumJob-Master" />
				<constructor-arg name="jobClass" value="com.yuntu.master.job.systems.MasterUserCustomerVisitLinkSumJob" />
				<constructor-arg name="shardingTotalCount" value="1" />
				<constructor-arg name="cron" value="0 */10 * * * ?" />
				<property name="overwrite" value="${job.overwrite}"/>
				<property name="description" value="计算潜客的的浏览次数和最后查看时间"/>
			</bean>
		</constructor-arg>
	</bean>
>

**Comment by zhangzhenhuajack** [comment]
重启tomcat，基本上可以解决问题？但是不能经常重启来解决问题的？

**Comment by terrymanu** [comment]
能描述的清楚点么。
有无error log
dump出来看看zk状态
有何重现条件

**Comment by zhangzhenhuajack** [comment]
挺频繁的，几乎每天都有这种情况！只是有一个job执行时间很长，会影响吗？

**Comment by terrymanu** [comment]
请更新重现条件

**Comment by zhangzhenhuajack** [comment]
之前是1.0.1，目前升级到了1.0.5再没有出现过这种问题了！
