### ISSUE TITLE
[Bug]流式处理且失效转移时，失效转移的分片项不能执行一次即停止

### ISSUE THREAD

**Issue by peng6812** [dangdangdotcom/elastic-job#74]
机器一处理5-9分片的数据，机器二处理0-4分片的数据，前提条件：所有分片数据均能一直取到数据，
当机器二down机，进入失效转移阶段，理论上机器一由于一直能取到数据，不会处理失效转移的分片数据，但是机器一会由于重新需要分片，跳出流式处理循环，在下一次execute中，会遇到jobFacade.failoverIfNecessary(); 这样导致会接受分片4的失效转移数据，从而进入4分片的流式处理阶段，导致正常的5-9分片数据得不到处理
![image](https://cloud.githubusercontent.com/assets/17996475/13940460/6458748e-f018-11e5-8b49-f3ded6810463.png)

**Comment by terrymanu** [comment]
原因查明：失效转移时，重新触发作业会导致重新分片而清理掉分片标记，导致失效转移的作业不会停止。与原意违背。
原意是想失效转移只执行一次，然后发现需要重新分片的标记而停止流式处理。
