### ISSUE TITLE
spring 兼容问题

### ISSUE THREAD

**Issue by peng6812** [dangdangdotcom/elastic-job#75]
![image](https://cloud.githubusercontent.com/assets/17996475/13949283/1c119c04-f05f-11e5-93dd-a290e5d007c7.png)
![image](https://cloud.githubusercontent.com/assets/17996475/13949298/2b91e9e0-f05f-11e5-9366-11470e6cfd82.png)
采用spring 3.2.3

**Comment by terrymanu** [comment]
esjob未考虑支持低版本spring的问题。esjob公三种配置方式，如有需要，可考虑不使用job的命名空间。
