### ISSUE TITLE
PropertyPlaceholderConfigurer的配置方式不支持

### ISSUE THREAD

**Issue by fengkar** [dangdangdotcom/elastic-job#79]
org.springframework.beans.factory.config.PropertyPlaceholderConfigurer

**Comment by terrymanu** [comment]
请问spring使用的什么版本

**Comment by lsk12162015** [comment]
我也是同样的问题，我用的是spring-3.1.2

**Comment by terrymanu** [comment]
我们并不承诺支持elastic-job官方使用的版本更低的版本。
目前elastic-job使用的是spring 4.x，暂时不会考虑支持spring 3.x。

如果想使用spring 3.x，可以考虑不使用elastic-job提供的spring命名空间。
