### ISSUE TITLE
elastic-job管理端后台无法查看当前应用的JOB情况

### ISSUE THREAD

**Issue by bwzhang2011** [dangdangdotcom/elastic-job#80]
Hi，测试1.0.6版本时，使用其管理段无法查看到应用运行的JOB情况。我的设置如下
1. JOB的配置：
serverLists=192.168.234.36:2181,192.168.234.79:2181,192.168.234.159:2181
namespace=course-elasticJob
baseSleepTimeMilliseconds=1000
maxSleepTimeMilliseconds=3000
maxRetries=3

nestedPort=4181
nestedDataDir=course/schedule_data/

2.管理段配置:
注册中心名称：courseschedule	
连接地址：192.168.234.36:2181,192.168.234.79:2181,192.168.234.159:2181	
命名空间：course-elasticJob

运行应用后，能打印其jOB触发情况（但是无法从管理端却无法看到作业情况），求原因和解答

**Comment by bwzhang2011** [comment]
@terrymanu, 能否指点一二。JOB可以在控制台打印，但管理段配置了命名空间，却无法提取。而我在zookeeper-web管理段 是看到路径已经写入到zookeeper了。

**Comment by terrymanu** [comment]
你使用的是内置zk，但是却用控制台连外置zk，所以看不到信息。
nestedPort=4181
nestedDataDir=course/schedule_data/
这两个字段用于开启内置zk。

请勿再次提问，如有问题请在qq群讨论。issue仅用于开发新功能和修改bug。谢谢合作

**Comment by bwzhang2011** [comment]
@terrymanu, 抱歉。我没有弄清楚这个差别。这个对刚接触的可能没去细微理解这个差别，我已经加入QQ了，再次感谢不吝指出。
