### ISSUE TITLE
stop 作业 报空指针

### ISSUE THREAD

**Issue by timqq** [dangdangdotcom/elastic-job#83]
作业服务器和zk 连接断掉 触发 ConnectionState.LOST 事件  时停止作业 而没有跑过的作业 还没放到instanceMap中 导致 报空指针 可以判断下是否存在  其他如 和 ConnectionState.RECONNECTED 事件 也是同样的问题

**Comment by terrymanu** [comment]
目前instanceMap应该无人使用，我们打算删除了。
不知你说的是否为schedulerMap。

**Comment by timqq** [comment]
是 instanceMap

**Comment by terrymanu** [comment]
请问哪里的代码使用了instanceMap

**Comment by timqq** [comment]
JobScheduler：
 
   public void stopJob() {
        try {
            JobRegistry.getInstance().getJobInstance(jobConfiguration.getJobName()).stop();
            scheduler.pauseAll();
        } catch (final SchedulerException ex) {
            throw new JobException(ex);
        }
    }

**Comment by terrymanu** [comment]
这是是老代码，新的已经不是这样了

**Comment by terrymanu** [comment]
instanceMap已删除
