### ISSUE TITLE
作业开始是禁用启动，然后在控制台也不能启动

### ISSUE THREAD

**Issue by jxctx88** [dangdangdotcom/elastic-job#84]
simpleJob.disabled=true  
simpleJob.overwrite=true
这样设置后，在控制台也不能启动了

**Comment by fzsens** [comment]
控制台中的恢复，是特定对停止(stop)而言的，具体是删除Zk在~/servers/ip/下的stoped节点。
而disabled属性，作用应该是设定作业为不可以用，在初始化ServerService的时候会在Zk的~/services/ip/下添加disabled节点，标识该机器对应的job是不可用的。
你可以手工删除对应的disabled节点，观察下结果。

**Comment by gl2001wl** [comment]
提交了一个pull request可以看下：
https://github.com/dangdangdotcom/elastic-job/pull/86
我们也有这个需求，启动的时候某些job或者server默认不启动，后续需要动态调整

**Comment by terrymanu** [comment]
已merge， 感谢贡献代码
