### ISSUE TITLE
[Bug] console配置为集群模式时，点击切换监控job造成注册中心紊乱

### ISSUE THREAD

**Issue by gl2001wl** [dangdangdotcom/elastic-job#94]
当使用多台机器部署console，轮询负载模式后，就是每次请求可能发送到不同的服务器。
在console中不断点击作业总览中的job，会造成注册中心紊乱，有时显示为连接注册中心。
注：已经在集群每个节点上连接了同样的注册中心

看了下这里使用了session，这种场景能否不使用session？使用cookie或者返还前端，之后的每次请求再带过去？

**Comment by terrymanu** [comment]
为什么要使用多台机器部署console，只是个控制台，一台应该就够了
