### ISSUE TITLE
web项目 reg:zookeeper 属性配置引用配置项启动失败

### ISSUE THREAD

**Issue by panshiming** [dangdangdotcom/elastic-job#96]
<reg:zookeeper id="regCenter" serverLists="10.1.15.80:2181" namespace="my-task" baseSleepTimeMilliseconds="${baseSleepTimeMilliseconds}" maxSleepTimeMilliseconds="3000"  maxRetries="3" nestedPort="2181" nestedDataDir="target/test_zk_data/" />
引用"${baseSleepTimeMilliseconds}" 不成功，非web工程可以，请问下这个和<reg:zookeeper 模板有关么

**Comment by haocao** [comment]
Duplicated with #141
