### ISSUE TITLE
1.0.8【bug】 在控制台点击失效时，后台狂刷日志

### ISSUE THREAD

**Issue by gaoyaqiu** [dangdangdotcom/elastic-job#98]
操作步骤：
1. 控制台点击某一个Job的失效按钮
2. 查看Job后台日志，狂刷如下日志
[JOB] 2016-05-27-18:01:56.435 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:56.541 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:56.541 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:56.646 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:56.646 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:56.751 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:56.751 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:56.856 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:56.857 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:56.966 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:56.967 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:57.072 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:57.072 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:57.180 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:57.181 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.
[JOB] 2016-05-27-18:01:57.287 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.r.e.RegExceptionHandler - Elastic job: ignored exception for: KeeperErrorCode = NoNode for /cy-job/F189CF70C0A8C779738B8A8DE7F67C01/leader/election/host
[JOB] 2016-05-27-18:01:57.287 [DEFAULT.F189CF70C0A8C779738B8A8DE7F67C01_Scheduler_Worker-1] DEBUG c.d.d.j.i.sharding.ShardingService - Elastic job: sleep short time until sharding completed.

**Comment by terrymanu** [comment]
可以详细说说重现条件么，比如多少个实例，什么类型的作业。
最好提供下dump文件。
我这里没有重现

**Comment by ravenwoo** [comment]
我也遇到了。。求问是啥原因造成的？ 后面是如何解决的？

**Comment by IcyLemon** [comment]
我也遇到了这个日志狂刷的问题。我的场景是：已经有一台作业服务器，上面的作业也正常运行。当启动另一台相同的作业服务器（相当于集群）时，就会狂刷日志。停止该服务器，再次启动，就不会再刷新的。
目前还没有找到复现条件。
